import type { CompleteLocalizationResource } from "../types/localization.js";

/**
 * English (United States) translations for Pocket Trash.
 *
 * This catalog is checked against `CompleteLocalizationResource` from
 * `src/types/localization.ts`. When adding a translation key, update that type
 * first, then add the required English string here. Other locale catalogs can
 * omit most new keys until a translation is available; omitted keys fall back to
 * this `en-US` catalog at runtime.
 */
export const enUS = {
  app: {
    name: "Pocket Trash",
  },
  action: {
    cancel: "Cancel",
    save: "Save",
  },
  error: {
    generic: "Something went wrong.",
  },
  locale: {
    current: "Current language: {locale}",
  },
  catalog: {
    configurationSlots: {
      actuator: "Actuator",
      appearance: "Appearance",
      clip: "Clip",
      material: "Material",
      mechanism: "Mechanism",
      tip: "Tip",
      topCap: "Top cap",
    },
    markets: {
      global: "Global",
    },
    penNoseProfiles: {
      cone: "Cone",
      round: "Round",
      step: "Step",
    },
    penPartRoles: {
      actuator: "Actuator",
      clip: "Clip",
      mechanism: "Mechanism",
      tip: "Tip",
      topCap: "Top cap",
    },
    productTypes: {
      pen: "Pen",
      "pen-actuator": "Pen actuator",
      "pen-clip": "Pen clip",
      "pen-mechanism": "Pen mechanism",
      "pen-tip": "Pen tip",
      "pen-top-cap": "Pen top cap",
      refill: "Refill",
    },
    refillCompatibilityGroups: {
      energel: "EnerGel",
      parkerG2: "Parker-style G2",
      pilotG2: "Pilot G2",
    },
  },
  web: {
    site: {
      name: "Pocket Trash",
    },
    changelog: {
      allCategories: "All categories",
      copyFailed: "Couldn’t copy link",
      copyLink: "Copy link",
      dateModified: "Date Modified",
      datePublished: "Date",
      empty: "No changelog entries yet.",
      emptyCategory: "No entries in this category.",
      linkCopied: "Link copied",
      nextPage: "Next page",
      pageStatus: "Page {page} of {pageCount}",
      previousPage: "Previous page",
    },
    action: {
      addCollection: "Add collection",
      addColor: "Add colour",
      addFinish: "Add finish",
      addFinishOption: "Add finish option",
      addMaker: "Add maker",
      addMaterial: "Add material",
      addProduct: "Add product",
      addToCollection: "Add to collection",
      archive: "Archive",
      clearAllFilters: "Clear all filters",
      clearCover: "Clear cover",
      clearSearch: "Clear search",
      close: "Close",
      confirmAdd: "Add another",
      deleteCover: "Delete cover",
      deleteImage: "Delete image",
      edit: "Edit",
      more: "More",
      moreFilters: "More filters",
      moveFinishOptionDown: "Move finish option down",
      moveFinishOptionUp: "Move finish option up",
      removeFinishOption: "Remove finish option",
      removeSelection: "Remove {name}",
      saveFlag: "Save flag",
      search: "Search",
      selectCover: "Use this cover",
      signIn: "Sign in",
      signOut: "Sign out",
      uploadImages: "Upload images",
      view: "View",
      viewCollection: "View collection",
      viewItem: "View item",
      viewProductDetails: "View product details",
      visitProductPage: "Visit product page",
    },
    admin: {
      config: {
        title: "Config and Settings",
        products: {
          description:
            "Search product types and choose which ones are parts or accessories.",
          noResults: "No product types match your search.",
          partOrAccessoryLabel: "Mark {name} as a part or accessory",
          searchPlaceholder: "Search product types",
          updated: "Updated {name}.",
          updateFailed: "Could not update {name}.",
        },
      },
      audit: {
        action: "Action",
        actor: "Actor",
        actorId: "Actor ID",
        after: "After",
        before: "Before",
        coverage: "Coverage starts {date}",
        coveredDomains: "Covered domains: {domains}",
        deleteAction: "Delete exported logs",
        deleteConfirmation: "I confirm I have downloaded these logs.",
        deletedUser: "Deleted user",
        description: "Review recorded administrative and product changes.",
        exportAction: "Export",
        exportDescription:
          "Download up to 10,000 oldest unexported events recorded more than 60 days ago. Downloaded copies remain the operator's responsibility.",
        exportReasonPlaceholder: "Explain why these audit logs are needed",
        exportSummary:
          "Oldest {count} events recorded before {cutoff}, ending at {date}",
        exportTitle: "Export audit log",
        fromDate: "From date",
        metadata: "Metadata",
        noEvents: "No audit events match these filters.",
        noValue: "None",
        occurred: "Occurred",
        olderEvents: "Older events",
        owner: "Owner",
        reason: "Reason",
        target: "Target",
        targetId: "Target ID",
        targetType: "Target type",
        title: "Audit log",
        toDate: "To date",
      },
      featureFlags: {
        actions: "Actions",
        adminOnlyTargeting: "Admin-only targeting",
        audience: "Audience",
        booleanControls:
          "Boolean controls for global, private, and beta surfaces.",
        description: "Description",
        displayName: "Display name",
        editFlag: "Edit flag",
        emailUsernameOrName: "Email, username, or name",
        featureFlags: "Feature flags",
        flag: "Flag",
        flags: "Flags",
        globalDefaultEnabled: "Global default enabled",
        newFlag: "New flag",
        searchUsers: "Search users",
        slugPlaceholder: "new-library-ui",
      },
      makers: {
        description: "Manage maker profiles and public URLs.",
        editMaker: "Edit {name}",
        empty: "No makers found.",
        imageAction: "{action} {fileName}",
        imagesEmpty: "No maker images yet.",
        rootUrl: "Website",
        title: "Makers",
      },
      users: {
        active: "Active",
        ban: "Ban user",
        banned: "Banned",
        description: "Search users and manage account access.",
        noResults: "No users found.",
        pendingBan: "Ban pending",
        pendingUnban: "Unban pending",
        reasonPlaceholder: "Explain this access decision",
        title: "User access",
        unban: "Unban user",
        updated: "User access updated.",
        updateReason: "Update reason",
      },
      hub: {
        catalogImageTrash: "Catalog image trash",
        description: "Manage Pocket Trash administration.",
        materials: "Materials",
        title: "Admin Panel",
      },
      notifications: {
        title: "Notifications",
      },
      settings: {
        title: "Admin settings",
        linear: {
          title: "Linear",
          description: "Connect Linear to plan approved feedback requests.",
          connect: "Connect Linear",
          connectedAs: "Connected as {name}",
          update: "Update connection",
          remove: "Remove connection",
          needsUpdate: "Update the connection to grant write access.",
          actionFailed: "We couldn't update the Linear connection.",
        },
      },
      trash: {
        title: "Trash",
      },
    },
    archive: {
      closeSearch: "Close search",
      controls: "Archive controls",
      defaultPenDescription: "{siteName} pen.",
      filterDescription:
        "Filter the archive by category, size, material, and more.",
      filters: "Filters",
      itemCount: "{visible} of {total} items",
      noDescription: "(no description on file)",
      noItems: "No items match these filters.",
      searchPlaceholder: "Search...",
      searchProducts: "Search pens by title, specs, or description",
      sortLabel: "Sort",
      sortProducts: "Sort pens",
      sortDescription: "Choose how the archive is ordered.",
      footer: {
        fanMade: "Made by a fan; not affiliated with any maker.",
        productOwnership:
          "Product names, images, and descriptions remain the property of their respective owners.",
        resourceFor: "A resource for",
        suggestionsOrContact: "Suggestions or contact:",
        discord: "and the Machined Pens Discord.",
      },
      headline: {
        grip: "{size} Grip",
        mechanism: "{size} Mechanism",
        pen: "Pen",
      },
      lightbox: {
        archived: "Archived - no longer listed",
        closeProductDetails: "Close product details",
        nextImage: "Next image",
        previousImage: "Previous image",
        released: "Released",
        specsDescription:
          "Specs, materials, and release details for this product.",
      },
      filter: {
        all: "all",
        any: "any",
        matchMode: "{label} match mode",
        bodyDetails: "Body details",
        category: "Category",
        clip: "Clip",
        finish: "Finish",
        material: "Material",
        mechanism: "Mechanism",
        refill: "Refill",
        size: "Size",
        tipNose: "Tip / Nose",
      },
      sort: {
        newestDrop: "Newest drop",
        oldestDrop: "Oldest drop",
        priceLowToHigh: "Price low to high",
        priceHighToLow: "Price high to low",
        weightLightToHeavy: "Weight light to heavy",
        weightHeavyToLight: "Weight heavy to light",
        diameterThinToThick: "Diameter thin to thick",
        diameterThickToThin: "Diameter thick to thin",
        titleAToZ: "Title A to Z",
      },
      spec: {
        diameter: "Diameter",
        length: "Length",
        model: "Model",
        price: "Price",
        weight: "Weight",
      },
      state: {
        archived: "Archived",
      },
    },
    catalog: {
      allProducts: "All Products",
      approval: {
        approve: "Approve product",
        collectionItem: {
          approve: "Approve collection item",
          reject: "Reject collection item",
          title: "Collection item approval",
        },
        reasonLabel: "Decision reason",
        reasonPlaceholder: "Explain this approval decision",
        reject: "Reject product",
        reverse: "Return to pending",
        status: {
          approved: "Approved",
          pending: "Pending review",
          rejected: "Rejected",
        },
        title: "Product approval",
      },
      collectionsWithProduct: "Collections with this product",
      colorEffect: {
        fade: "Fade",
        solid: "Solid",
      },
      defaultButton: "Default Button",
      deletion: {
        action: "Permanently delete product",
        blocked:
          "This product is used by a collection or another product and cannot be deleted.",
        confirmation:
          "I understand that deleting this product and its images cannot be undone.",
        description:
          "Permanently delete {name}? Its images, finish options, material links, and specifications will be removed. This cannot be undone.",
        failed: "We couldn't delete this product. Try again.",
        title: "Delete product",
      },
      error: {
        bearingLength: "Enter 200 characters or fewer.",
        colorHex: "Choose a valid colour.",
        colorEffectRequired: "Select a colour effect.",
        colorEffectWithoutColors: "Add a colour or remove the colour effect.",
        descriptionLength: "Enter 5,000 characters or fewer.",
        duplicate: "That name already exists.",
        duplicateComponent: "Each finish or colour can only be selected once.",
        duplicateFinishOption: "That finish option is already listed.",
        fadeColors: "Select at least two colours for a fade.",
        finishOptionRequired: "Add at least one finish option.",
        finishRequired: "Select at least one finish.",
        form: "We couldn't save this. Check the fields and try again.",
        positive: "Enter a number greater than zero.",
        productFinishRequired:
          "Select a product finish or create a custom finish.",
        productMaterialRequired: "Select a material offered by this product.",
        required: "This field is required.",
        url: "Enter a valid URL.",
      },
      field: {
        bearing: "Bearing",
        button: "Button",
        buttonDiameter: "Button diameter",
        colorEffect: "Colour effect",
        colorValue: "Colour value",
        colors: "Colours",
        description: "Description",
        finishes: "Finishes",
        finishOptions: "Finish options",
        maker: "Maker",
        makerProductUrl: "Maker product URL",
        materials: "Materials",
        measurementUnit: "{field} unit",
        name: "Name",
        productType: "Product type",
        rootUrl: "Maker URL",
        slug: "Slug",
        spinDiameter: "Spin diameter",
        thickness: "Thickness",
        thicknessWithButton: "Thickness with button",
        width: "Width",
      },
      filter: {
        description:
          "Filter by product type, material, finish, colour, and maker.",
        fadeName: "{colors} fade",
        moreOptions: "More {label}",
        productTypeAll: "All product types",
      },
      help: {
        collectionDescriptionOverride:
          "Leave blank to use the product description. Markdown supported. 5,000 characters maximum.",
        makerProductUrl: "Direct link to the product on the maker's website.",
        markdownDescription: "Markdown supported. 5,000 characters maximum.",
      },
      images: {
        aspectRatioGuideLink: "Read the image size and resolution guide",
        aspectRatioWarning:
          "This image is not 4:3 and will be cropped when displayed.",
      },
      finishOptionCount: "Finish options: {count}",
      finishPreview: "Preview: {finish}",
      materialCount: "Materials: {count}",
      noProducts: "No products yet.",
      notImplemented: "This product type is not implemented yet.",
      partsAndAccessories: "Parts and Accessories",
      selectColorEffect: "Select a colour effect",
      selectColors: "Select colours",
      selectFinishes: "Select finishes",
      selectFinishOption: "Select a finish option",
      selectMaker: "Select a maker",
      selectMaterial: "Select a material",
      selectMaterials: "Select materials",
      selectProductType: "Select a product type",
    },
    slider: {
      productType: {
        slider: "Slider",
        plate: "Slider plate",
        insert: "Slider insert",
        spinner: "Spinner",
        spinnerButton: "Spinner button",
      },
      alias: {
        add: "Add terminology alias",
        canonicalLabel: "Canonical term: {label}",
        managementLabel: "Maker terminology",
        matchedContext: "Matched term: {alias}",
        preferred: "Preferred",
        preferredMakerLabel: "Maker term: {alias}",
      },
      capability: {
        label: "Insert use",
        bodyHosted: "Body-hosted",
        insertDriven: "Insert-driven",
        notRecorded: "Magnet host not recorded",
        sliderBodyHoldsMagnets: "Slider body holds magnets",
        usesInserts: "This slider uses inserts",
      },
      measurement: {
        basis: "Measurement basis",
        setLevel: "Complete matched set",
        setLevelHelp:
          "Plate and insert measurements and weight describe the complete matched set.",
      },
      appearance: {
        label: "Appearance",
        materialRequired: "Material is required",
        optional: "Appearance is optional",
        none: "No appearance selected",
        pattern: "Pattern",
        patterns: "Patterns",
        selectPattern: "Select a pattern",
      },
      layout: {
        label: "Magnet layout",
        option: "{layout} — {count}-click",
        help: "{layout} has {rows} rows, {columns} lengthwise positions, {slots} slots per side, and {clicks} clicks.",
      },
      setup: {
        title: "Magnet setup",
        default: "Default setup",
        defaultDescription:
          "The live setup advertised by the catalog. It does not create a saved custom setup.",
        advertisedDefault: "Advertised default",
        availableOffers: "Available insert setups",
        offer: "Setup offer",
        selectOffer: "Select a setup offer",
        custom: "Custom setup",
        fromScratch: "Build from scratch",
        liveCatalog: "Live catalog setup",
        sourceNote: "Source note",
        clickCount: "Click count",
        clicks: "{count} clicks",
        notRecorded: "Not recorded",
      },
      magnet: {
        advanced: "Set custom magnet configuration or strengths",
        clear: "Clear magnet configuration",
        configuration: "Magnet configuration",
        configurations: "Magnet configurations",
        deletePresetConfirmation: 'Delete the preset "{name}"?',
        differentSides: "Use a different configuration for side B",
        layoutChanged:
          "The magnet configuration was cleared because the physical layout changed.",
        position: "Side {side}, position {position}",
        preset: "Preset",
        presets: "Magnet presets",
        selectPreset: "Select a preset",
        vocabularyLabel: "Configuration label",
        halfA: "Half A",
        halfB: "Half B",
        slot: "Magnet slot",
        slots: "Magnet slots",
        group: "Magnet group",
        groups: "Magnet groups",
        size: "Magnet size",
        grade: "Choose magnet strength for all magnets",
        row: "Documented row",
        column: "Documented column",
        insertionPosition: "Insertion position {position}",
        state: {
          occupied: "Occupied",
          empty: "Empty",
          unknown: "Unknown",
        },
      },
      relationship: {
        addInsert: "Add insert",
        plates: "Plates",
        inserts: "Inserts",
        includedInsert: "Included insert",
        includedPlates: "Included plates",
        addPlates: "Add plates",
        includedComponents: "Included components",
        included: "Included",
        installed: "Installed",
        availableInsertOffers: "Available insert offers",
        inclusionHelp:
          "Included parts describe what is sold with this product. They do not create collection items.",
      },
      component: {
        plateSet: "Plate set",
        insertSet: "Insert set",
        spare: "Spare",
        installedPlate: "Installed plate",
        installedInsert: "Installed insert",
        noPlate: "No plate installed",
        noInsert: "No insert installed",
        createIncluded: "Create included component",
        linkExisting: "Link existing component",
        install: "Install component",
        uninstall: "Uninstall component",
        replace: "Replace component",
        detach: "Detach component",
        moveAssembly: "Move complete assembly",
        moveAssemblySummary:
          "Moving this item also moves {count} connected assembly items.",
        uninstallBeforeTransfer:
          "Uninstall this component before installing it on another slider.",
        deleteSliderKeepsComponents:
          "Deleting this slider leaves its components as standalone spares.",
        deleteComponentDetaches:
          "Deleting this installed component detaches it from the assembly.",
      },
      search: {
        label: "Search catalog and collections",
        placeholder: "Search products, makers, types, aliases, or owners",
        matchedAliasContext: "Matched alias: {alias}",
        matchedTypeContext: "Matched product type: {type}",
        ownerMatchContext: "Matched owner: {owner}",
        noResults: "No products or collection items match this search.",
      },
      filter: {
        description:
          "Filter by material, finish, colour, maker, type, pattern, or exact component.",
        pattern: "Pattern",
        plate: "Slider plate",
        spinnerButton: "Spinner button",
        any: "Match any selected option",
        all: "Match all selected options",
        resultsAnnouncement: "{count} matching results",
      },
      privacy: {
        inherited: "Inherited privacy",
        inheritedDescription:
          "This installed component follows the privacy of its parent slider or spinner.",
        inheritedHelp:
          "Use the information button with a pointer, keyboard, or touch to learn why this privacy setting is read-only.",
        savedPreference:
          "Your saved component privacy preference resumes when the component is detached.",
        staffForcedPrivate: "Staff required this component to remain private.",
        blockingComponent:
          "{component} prevents this assembly from being public.",
      },
      moderation: {
        blockedTitle: "Action blocked",
        publicBlocked:
          "This assembly cannot be public because an installed component is unavailable or staff-private.",
        installBlocked:
          "This component cannot be installed because its moderation state conflicts with the assembly.",
        unavailableComponent: "Unavailable component",
      },
      validation: {
        capabilityRequired: "Choose whether this slider uses inserts.",
        bodyHostedInsert: "This slider does not use inserts.",
        insertMaterial: "Select exactly one material for an insert.",
        alreadyInstalled:
          "This component is already installed on another slider.",
        differentOwner: "Every assembly item must have the same owner.",
        unapproved: "Only approved catalog products can be installed.",
        exactProduct: "Select an option from this exact catalog product.",
        onePlate: "A slider can have at most one installed plate.",
        oneInsert:
          "An insert-driven slider can have at most one installed insert.",
        clickOption: "Select a current click option from this insert.",
        completeConfiguration:
          "Catalog configurations must record every required slot.",
        unknownSlot: "Catalog configurations cannot contain unknown slots.",
        incompleteSlot: "Complete every magnet slot before saving.",
        overlappingGroup: "A magnet slot can belong to only one group.",
        positiveDimension: "Enter a dimension greater than zero.",
        crossConfiguration:
          "Magnet groups cannot reference slots from another configuration.",
        advertisedDefault: "Select no more than one advertised default.",
      },
      confirmation: {
        createIncluded:
          "Create this included component as a new collection item?",
        linkIncluded: "Link an existing collection item as this component?",
        install: "Install {component} on {slider}?",
        uninstall: "Uninstall {component} and keep it as a spare?",
        replace:
          "Replace {current} with {replacement}? The current component will remain as a spare.",
        moveAssembly: "Move the complete installed assembly to {collection}?",
        deleteStandalone:
          "Permanently delete this standalone item? This cannot be undone.",
        deleteInstalledComponent:
          "Permanently delete this component and detach it from the assembly?",
        deleteSlider:
          "Permanently delete this slider and keep its components as spares?",
      },
      empty: {
        noOffers: "No setup offers are available.",
        noSearchResults: "No slider products match this search.",
        noFilterResults: "No slider products match these filters.",
      },
    },
    collections: {
      add: {
        title: "Add collection",
      },
      cover: {
        clearConfirmation:
          "Clear the current cover? The image will remain in the gallery.",
        current: "Current cover",
        deleteConfirmation:
          "Permanently delete this cover image? This cannot be undone.",
        history: "Previous covers",
      },
      directory: {
        avatar: "Generic collector avatar",
        itemCount: "Collection items: {count}",
        matchingItemCount: "{matching} of {total} collection items",
      },
      deletion: {
        deleteConfirmation:
          "I understand that deleting this collection, its items, and their images cannot be undone.",
        deleteChoice: "Permanently delete collection and items",
        destination: "Destination collection",
        itemAction: "Permanently delete item",
        itemConfirmation:
          "I understand that deleting this item and its images cannot be undone.",
        itemDescription:
          "Permanently delete {name} from its collection? Its images and finish selection will be removed. Linked items and catalog products will be kept; any installed-component link to this item will be cleared, and components installed on this item will remain as spares.",
        moveAction: "Move items and delete",
        moveChoice: "Move items, then delete collection",
        moveConfirmation:
          "I understand that this collection and its cover images will be permanently deleted. Moved items and their images will be kept.",
        moveSummary: "Move {count} items to {destination}.",
        noDestination: "Create another collection before moving items.",
        open: "Delete or archive",
      },
      duplicateWarning:
        "Matching products already owned: {count}. Confirm to add another.",
      edit: {
        noFields:
          "There are no collection-specific fields to edit for this item.",
        title: "Edit collection",
      },
      empty: "No collection items yet.",
      emptyCollections: "You don't have any collections yet.",
      error: {
        chooseCollection: "Choose a collection.",
        syncIncomplete: "Your profile is still syncing. Try again.",
        upload:
          "The collection was saved, but its images could not be uploaded. Try again from Edit collection.",
      },
      gallery: {
        deleteConfirmation:
          "Permanently delete this collection image? This cannot be undone.",
        imagesHelp:
          "Choose 1–{maxImages} images. If the collection has no cover, the first image becomes the cover. Each image can be up to {maxFileSize}; all files in this upload can total up to {maxSessionSize}.",
        nextPage: "Next page",
        owner: "Owner: {owner}",
        pageStatus: "Page {page} of {pageCount}",
        previousPage: "Previous page",
        title: "Gallery",
      },
      field: {
        collection: "Collection",
        cover: "Cover image",
        description: "Description",
        displayName: "Display name",
        name: "Name",
        serialNumber: "Serial number",
        summary: "Summary",
      },
      finishChoice: {
        custom: "Custom finish",
        product: "Product finish",
      },
      placeholder: {
        description: "Describe this collection",
        name: "Collection name",
        summary: "Summarize this collection",
      },
      select: {
        addNew: "Add new collection",
        placeholder: "Select a collection",
      },
      serial: {
        hasSerialNumber: "This item has a serial number",
      },
      visibility: {
        privateCallout:
          "This item is public, but it will remain hidden while its collection is private.",
      },
    },
    pens: {
      admin: {
        action: {
          "compatibility-assertion": "Add compatibility assertion",
          "compatibility-evidence": "Add compatibility evidence",
          "compatibility-group": "Add compatibility group",
          "compatibility-membership": "Add compatibility membership",
          "configuration-choice": "Add configuration choice",
          "configuration-rule": "Add configuration rule",
          "configuration-slot": "Add configuration slot",
          "configuration-slot-required": "Set required configuration slot",
          market: "Add market",
          "offering-identifier": "Add offering identifier",
          "offering-market-status": "Add offering market status",
          "refill-ink-color": "Add refill ink colour",
          "refill-offering": "Add refill offering",
          "refill-tip-style": "Add refill tip style",
          "source-evidence": "Add source evidence",
        },
        actionLabel: "Action",
        aliases: "Aliases",
        and: "and",
        approved: "Approved",
        availableWhen: "Available when",
        availableWhenAnd: "Required choices (all)",
        captureDate: "Capture date",
        catalogEdition: "Catalogue edition",
        choice: "Choice",
        claim: "Claim",
        code: "Code",
        compatibilityGroup: "Compatibility group",
        displayName: "Display name",
        effectiveDate: "Effective date",
        evidence: "Evidence",
        evidenceKind: {
          curatedObservation: "Curated observation",
          dimensionalComparison: "Dimensional comparison",
          manufacturerStatement: "Manufacturer statement",
          physicalFitTest: "Physical fit test",
        },
        evidenceKindLabel: "Evidence kind",
        explanation: "Explanation",
        firstFormat: "First format",
        firstSourceUrl: "First source URL",
        heading: "Pens administration",
        identifier: "Identifier",
        identifierKind: {
          makerCode: "Maker code",
          sku: "SKU",
        },
        identifierKindLabel: "Identifier kind",
        inkColor: "Ink colour",
        lifecycle: {
          current: "Current",
          discontinued: "Discontinued",
          historical: "Historical",
        },
        lifecycleLabel: "Lifecycle",
        localizationKey: "Localization key",
        market: "Market",
        marketKind: {
          country: "Country",
          region: "Region",
        },
        marketKindLabel: "Market kind",
        mechanism: "Mechanism",
        name: "Name",
        offering: "Offering",
        originalUrl: "Original URL",
        outcome: {
          compatible: "Compatible",
          conditional: "Conditionally compatible",
          incompatible: "Incompatible",
          variable: "Variable",
        },
        outcomeLabel: "Outcome",
        pen: "Pen",
        procedure: "Procedure",
        publisher: "Publisher",
        refill: "Refill",
        refillModel: "Refill model",
        registeredGroup: "Registered group",
        remedy: "Remedy",
        required: "Required",
        result: "Result",
        secondFormat: "Second format",
        secondSourceUrl: "Second source URL",
        slot: "Configuration slot",
        slotKind: "Slot kind",
        slug: "Slug",
        sourceDate: "Source date",
        sourceKind: "Source kind",
        sourceUrl: "Source URL",
        summary: "Summary",
        target: "Target",
        targetChoice: "Target choice",
        targetType: {
          group: "Compatibility group",
          refill: "Refill",
        },
        targetTypeLabel: "Target type",
        testDate: "Test date",
        tipSize: "Tip size",
        tipStyle: "Tip style",
        warning: "Warning",
      },
      collection: {
        noRefill: "No refill installed",
        noRefillOffering: "No refill offering selected",
        notSupported: "Not supported by this configuration",
        refill: "Installed refill",
        refillOffering: "Refill offering",
      },
      configuration: {
        availableWhen: "Available when {requirements}",
        heading: "Configuration",
        required: "Required",
        unknownChoice: "Unknown choice",
      },
      field: {
        aliases: "Aliases",
        refillModel: "Refill model",
      },
      productType: {
        actuator: "Pen actuator",
        clip: "Pen clip",
        mechanism: "Pen mechanism",
        pen: "Pen",
        refill: "Refill",
        tip: "Pen tip",
        topCap: "Pen top cap",
      },
      refill: {
        compatiblePens: "Compatible Pens",
        noCompatiblePens: "No compatible Pens recorded.",
        offerings: "Refill offerings",
        requiresTip: "Requires {tip}",
      },
    },
    currency: {
      aud: "$ AUD",
      cad: "$ CAD (native)",
      chf: "CHF",
      eur: "EUR EUR",
      gbp: "GBP GBP",
      jpy: "JPY JPY",
      nzd: "$ NZD",
      usd: "$ USD",
    },
    error: {
      expectedJsonRequestBody: "Expected a JSON request body.",
      invalidCurrencyCode: "Expected a valid currency code.",
      invalidDimensionUnit: "Expected a valid dimension unit.",
      invalidLocale: "Expected a valid locale.",
      invalidLogClientKey: "Invalid log client key.",
      invalidMeasurementSystem: "Expected a valid measurement system.",
      invalidTheme: "Expected a valid theme.",
      invalidWeightUnit: "Expected a valid weight unit.",
      missingSetting: "Expected at least one setting.",
      settingsSaveFailed: "We couldn't save your settings. Please try again.",
      userSettingsObject: "Expected a user settings object.",
    },
    erasure: {
      self: {
        title: "Delete account",
        description:
          "Permanently erase your Pocket Trash account and account-linked data.",
        open: "Delete my account",
        dialogTitle: "Delete your account?",
        dialogIntro: "Erasure starts immediately and cannot be canceled.",
        deletedData:
          "Your profile, settings, collections, collection items, resources, and uploaded files will be deleted.",
        productsRemain:
          "Products you submitted may remain in the catalog without attribution to you.",
        retention:
          "Backups, caches, and security logs may retain limited data until their documented retention periods expire.",
        publicCopies:
          "Copies saved or shared by other people cannot be recalled.",
        confirm: "I understand that this is permanent and cannot be canceled.",
        submit: "Permanently delete my account",
        failure: "Account erasure could not be started. Try again.",
      },
      status: {
        title: "Account erasure",
        processing: "Erasure in progress",
        processingDescription:
          "Your account is restricted while Pocket Trash removes your account-linked data.",
        needsSupport: "Erasure needs support",
        needsSupportDescription:
          "We could not complete every erasure step automatically. Contact support and include the request ID below.",
        completed: "Account erased",
        completedDescription:
          "Your Pocket Trash account and account-linked active-system data have been erased.",
        requestId: "Request ID: {requestId}",
        support: "Contact support",
      },
      admin: {
        navigation: "Account erasure",
        title: "Account erasure",
        description:
          "Start or retry a verified privacy request. Do not enter personal information in the request reference.",
        emailLabel: "Clerk account email",
        emailPlaceholder: "user@example.com",
        findTarget: "Find account",
        findingTarget: "Finding account…",
        targetNotFound: "No Clerk account matched that email.",
        targetLabel: "Target account",
        verificationMethodLabel: "How was the request verified?",
        authenticatedRequest: "Authenticated privacy request",
        verifiedEmail: "Manually verified Clerk email",
        referenceLabel: "Opaque request reference",
        referenceDescription:
          "Use a ticket or request ID. Do not enter a name, email address, or request details.",
        start: "Start erasure",
        starting: "Starting erasure…",
        requestTitle: "Erasure request",
        statusLabel: "Status: {status}",
        errorLabel: "Failure code: {errorCode}",
        retry: "Retry erasure",
        retrying: "Retrying erasure…",
        failure: "The erasure action failed.",
      },
      productNotice:
        "Products you submit may remain in the catalog without attribution after your account is erased.",
    },
    feedback: {
      title: "Feedback",
      board: {
        empty: "No active feedback matches your search.",
        error: "We couldn't load feedback.",
        loading: "Loading feedback…",
        searchLabel: "Search feedback",
        searchPlaceholder: "Search requests",
      },
      details: {
        open: "View details for {title}",
        title: "Request details",
      },
      duplicates: {
        description: "These requests may already cover your idea.",
        submitAnyway: "Submit anyway",
        title: "Similar requests",
        upvote: "Upvote this request",
      },
      new: {
        title: "Submit feedback",
        description: "Share an idea or report a problem.",
        titleLabel: "Title",
        titleHelp: "120 characters maximum.",
        descriptionHelp: "5,000 characters maximum.",
        categoryLabel: "Category (optional)",
        categoryPlaceholder: "Select a category",
        submit: "Submit request",
        submitting: "Submitting...",
        success: "Feedback submitted.",
        failure: "We couldn't submit this request.",
        limit: "You can have up to 60 active requests.",
      },
      myRequests: {
        title: "My requests",
        empty: "You haven't submitted any requests yet.",
        error: "We couldn't load your requests.",
        loading: "Loading requests…",
        nextPage: "Next page",
        noResults: "No requests match your search.",
        previousPage: "Previous page",
        searchLabel: "Search my requests",
        searchPlaceholder: "Search requests",
      },
      admin: {
        navigation: {
          allActive: "All active",
          active: "Planned",
          archive: "Archive",
          requests: "Requests",
        },
        plan: {
          action: "Plan",
          title: "Plan request",
          typeLabel: "Create in Linear",
          issue: "Issue",
          project: "Project",
          assignIssue: "Assign to me",
          leadProject: "Make me project lead",
          labels: "Labels",
          submit: "Create and plan",
          loading: "Loading Linear options…",
          success: "Request planned in Linear.",
          failure: "We couldn't create this in Linear. You can retry safely.",
          connectionRequired:
            "Connect or update Linear in Admin settings before planning.",
          settingsLink: "Open Admin settings",
        },
        sync: {
          action: "Sync",
          connectionRequired:
            "Connect or update Linear in Admin settings before syncing.",
          failure: "We couldn't synchronize this status from Linear.",
          success: "Feedback status synchronized.",
        },
        table: {
          actions: "Actions",
          category: "Category",
          status: "Status",
          submitted: "Submitted",
          submitter: "Submitter",
          title: "Title",
          updated: "Updated",
          votes: "Votes",
        },
        sort: {
          ascending: "Sort {column} ascending",
          descending: "Sort {column} descending",
          remove: "Remove {column} sorting",
        },
        requests: {
          title: "Feedback requests",
          empty: "There are no pending requests.",
          error: "We couldn't load pending requests.",
          loading: "Loading pending requests…",
          approve: "Approve",
          saveAndApprove: "Save & Approve",
          deny: "Deny",
          categoryRequired: "Select a category before approval.",
          approved: "Request approved.",
          denied: "Request denied.",
          detailsOpen: "Manage {title}",
          detailsTitle: "Manage request",
          merge: "Merge request",
          mergeTargetLabel: "Merge into",
          mergeTargetPlaceholder: "Select an active request",
          merged: "Request merged.",
          planRecoveryRequired:
            "Recover the unfinished Linear Plan attempt before denying this request.",
          updated: "Request updated.",
          actionFailed: "We couldn't update this request.",
          previousPage: "Previous page",
          nextPage: "Next page",
        },
        active: {
          empty: "There is no planned feedback.",
          error: "We couldn't load planned feedback.",
          loading: "Loading planned feedback…",
          nextPage: "Next page",
          previousPage: "Previous page",
          searchLabel: "Search planned feedback",
          searchPlaceholder: "Search planned requests",
          title: "Planned",
        },
        archive: {
          allStatuses: "All statuses",
          empty: "The feedback archive is empty.",
          error: "We couldn't load the feedback archive.",
          loading: "Loading the feedback archive…",
          nextPage: "Next page",
          noResults: "No archived feedback matches these filters.",
          previousPage: "Previous page",
          searchLabel: "Search archived feedback",
          searchPlaceholder: "Search archived requests",
          statusLabel: "Status",
          title: "Feedback archive",
        },
      },
      status: {
        canceled: "Canceled",
        completed: "Completed",
        denied: "Denied",
        inProgress: "In progress",
        merged: "Merged",
        pending: "Pending",
        planned: "Planned",
        requested: "Requested",
      },
      vote: {
        add: "Upvote",
        failure: "We couldn't update your vote.",
        permanent: "Your submission vote is permanent.",
        remove: "Remove vote",
      },
      category: {
        productType: "Product type",
        feature: "Feature",
        improvement: "Improvement",
        bug: "Bug",
        unset: "Not set",
      },
      metadata: {
        submittedOn: "Submitted {date}",
        submittedBy: "Submitted by {submitter}",
        votes: "{count} votes",
      },
      notification: {
        completed: "Completed",
        description: "Review submitted and completed feedback activity.",
        empty: "No feedback notifications.",
        submitted: "Submitted",
        title: "Feedback notifications",
      },
    },
    footer: {
      discordNewTab: "Discord (opens in a new tab)",
      tagline: "Made by EDC fans for EDC fans",
      xNewTab: "X (opens in a new tab)",
    },
    help: {
      comingSoon: "Coming soon.",
      contact: "Contact",
      dateModified: "Date Modified",
      datePublished: "Date",
      developmentCallout: "This page is still in development.",
      topics: "Help Topics",
    },
    markdownEditor: {
      mode: {
        visual: "Visual",
        source: "Source",
      },
      toolbar: {
        heading1: "Heading 1",
        heading2: "Heading 2",
        heading3: "Heading 3",
        bold: "Bold",
        italic: "Italic",
        strikethrough: "Strikethrough",
        link: "Link",
        unorderedList: "Bulleted list",
        orderedList: "Numbered list",
        table: "Table",
        horizontalRule: "Horizontal rule",
        blockquote: "Blockquote",
      },
      link: {
        text: "Link text",
        url: "URL",
        insert: "Insert link",
        update: "Update link",
        remove: "Remove link",
        invalidUrl: "Enter a relative, HTTP, or HTTPS URL.",
      },
      status: {
        loading: "Loading Markdown editor.",
        fallback:
          "The visual editor couldn't load. Continue editing in Source mode.",
      },
      count: {
        characters: {
          normal: "{current} / {limit} characters",
          warning: "{current} / {limit} characters, approaching limit",
          limitReached: "{current} / {limit} characters, limit reached",
          overLimit: "{current} / {limit} characters, {over} over limit",
        },
        words: {
          normal: "{current} / {limit} words",
          warning: "{current} / {limit} words, approaching limit",
          limitReached: "{current} / {limit} words, limit reached",
          overLimit: "{current} / {limit} words, {over} over limit",
        },
      },
    },
    materials: {
      specific: {
        title: "Alloys and grades",
        add: "Add alloy or grade",
        edit: "Edit alloy or grade",
        name: "Alloy or grade name",
        empty: "No alloys or grades have been added.",
        select: "Select an alloy or grade",
        optional: "Alloy or grade (optional)",
        general: "General only",
        help: "Choose an alloy or grade for this material, or leave it general.",
        noProducts: "No products use this alloy or grade yet.",
        noCollectionItems: "No collection items use this alloy or grade yet.",
        noImages: "No images have been added for this alloy or grade.",
      },
      slug: {
        help: "Renaming keeps the current slug. Select Update slug to change the URL.",
        update: "Update slug",
        preview: "New URL: {url}",
        confirmation:
          "Change {oldUrl} to {newUrl}? The old URL will stop working.",
        affected: "Nested material URLs affected: {count}",
      },
      admin: {
        addTitle: "Add material",
        created: "Material added.",
        description: "Add and edit material details and images.",
        editTitle: "Edit material",
        empty: "No materials found.",
        saved: "Material saved.",
        slugHelp: "The slug is permanent and cannot be changed.",
        title: "Materials",
      },
      count: {
        collectionItems: "Collection items: {count}",
        products: "Products: {count}",
      },
      detail: {
        collectionItems: "Collection items",
        collectionItemsPagination: "Collection item pages",
        noCollectionItems: "No collection items use this material yet.",
        noProducts: "No products use this material yet.",
        products: "Products",
        productsPagination: "Product pages",
      },
      directory: {
        description: "Browse materials used by products and collections.",
        empty: "No materials are available yet.",
        other: "Other",
        popular: "Popular Materials",
        tableOfContents: "Materials A to Z",
        title: "Materials",
      },
      image: {
        alt: "Image of {name}",
        scope: "Image scope",
        generalScope: "General",
        specificScope: "Alloy or grade",
        move: "Move image",
        moveConfirmation: "Move this image to {scope}?",
        moved: "Image moved.",
        archiveConfirmation: "Archive this material image?",
        empty: "No images have been added.",
        placeholder: "No image available for {name}",
        restore: "Restore image",
        restoreConfirmation: "Restore this material image?",
        uploadFailed:
          "The material was saved, but its images could not be uploaded. Try again from Edit material.",
        uploadHelp:
          "Choose up to {maxImages} images. Each image can be up to {maxFileSize}; all files in this upload can total up to {maxSessionSize}.",
      },
      validation: {
        duplicateImage: "This image has already been added.",
        invalidSpecific: "Choose an alloy or grade belonging to this material.",
        duplicateSpecific:
          "This alloy or grade name already exists for this material.",
        duplicateAssignment:
          "This material and alloy or grade combination is already selected.",
        parentNameConflict:
          "An alloy or grade cannot have the same name as its general material.",
        slugCollision: "This slug is already in use.",
        duplicateAtDestination:
          "This image already exists in the destination scope.",
        immutableParent:
          "The general material of an alloy or grade cannot be changed.",
      },
    },
    makers: {
      collectionItems: "Collection Items",
      collectionItemsPagination: "Maker collection items",
      collectionItemCount: "Collection items: {count}",
      detailDescription:
        "Browse public products and collection items by {name}.",
      directoryDescription:
        "Browse every maker represented in the Pocket Trash catalog.",
      empty: "No makers found.",
      imageAlt: "{name} maker image",
      imageCount: "Images: {count}",
      noCollectionItems: "No public collection items yet.",
      noProducts: "No public products yet.",
      other: "Other",
      popular: "Popular Makers",
      products: "Products",
      productsPagination: "Maker products",
      productCount: "Products: {count}",
      productMakerAttribution: "{productType} · {maker}",
      tableOfContents: "Maker directory",
      visitWebsite: "Visit maker website",
    },
    navigation: {
      account: "Account",
      accountMenu: "Account menu",
      admin: "Admin",
      betaFeatures: "Beta features",
      changelog: "Changelog",
      collections: "Collections",
      contact: "Contact",
      help: "Help",
      home: "Home",
      language: "Language",
      logOut: "Log out",
      materials: "Materials",
      makers: "Makers",
      privacy: "Privacy",
      products: "Products",
      resources: "Resources",
      selectLanguage: "Select language",
      termsOfService: "Terms of service",
      user: "User",
    },
    locale: {
      enUS: "English (US)",
      esMX: "Spanish (Mexico)",
    },
    page: {
      betaFeatures: {
        empty: "No beta features are available.",
      },
      collections: {
        empty: "Collections will be available later.",
      },
      error: {
        copied: "Copied",
        copyDetails: "Copy error details",
        copyFailed: "Copy failed",
        description: "We couldn't load this page. Try again.",
        retry: "Retry",
        retrying: "Retrying…",
        returnHome: "Return home",
        technicalDetails: "Technical details",
        title: "Something went wrong",
      },
      notFound: {
        description: "This page does not exist or is no longer available.",
        returnHome: "Return home",
        returnToArchive: "Return to archive",
        title: "Not found",
        unavailable: "Page unavailable",
      },
      resources: {
        stub: "Resources are coming soon.",
      },
    },
    resources: {
      action: {
        accept: "Accept",
        add: "Add Resource",
        closeImage: "Close image",
        collapseVersion: "Collapse version {version}",
        collapseVersionHistory: "Collapse version history",
        delete: "Move to trash",
        details: "Details",
        download: "Download",
        edit: "Edit",
        expandVersion: "Expand version {version}",
        expandVersionHistory: "Expand version history",
        markPrivate: "Mark private",
        nextImage: "Next image",
        permanentlyDelete: "Delete permanently",
        previousImage: "Previous image",
        removeFile: "Remove file",
        restore: "Restore",
        retry: "Retry",
        saveChanges: "Save changes",
        upload: "Add Resource",
        uploadNewVersion: "Upload new version",
      },
      add: {
        title: "Add Resource",
      },
      category: {
        all: "All categories",
        create: "Create “{category}”",
        filterLabel: "Filter by category",
        label: "Categories",
        noResults: "No categories found.",
        remove: "Remove {category}",
        search: "Search categories",
        select: "Select one or more categories",
        selectedCount: "Selected categories: {count}",
      },
      detail: {
        categories: "Categories",
        currentVersion: "Current version",
        downloadCount: "Downloads: {count}",
        fileSize: "Size: {size}",
        fileTypeFallback: "File",
        filename: "File: {filename}",
        imageAlt: "Image of {name}",
        noImage: "No image available",
        noPreview: "No preview image",
        notFound: "This resource is not available.",
        openImage: "Open {name}",
        previewAlt: "Preview of {name}",
        sharedBy: "Shared by",
        totalDownloadCount: "Total downloads: {count}",
        updatedOn: "Updated {date}",
        uploadedBy: "Uploaded by {uploader}",
        uploadedOn: "Uploaded {date}",
        version: "Version {version}",
        versionHistory: "Version history",
        versionUploadedOn: "Version {version}, uploaded {date}",
      },
      directory: {
        description: "Browse files shared by the Pocket Trash community.",
        empty: "No resources have been uploaded yet.",
        emptyFiltered: "No resources match these category filters.",
        filters: "Resource filters",
        invalidFilter: "One or more category filters are invalid.",
        loading: "Loading resources…",
        searchPlaceholder: "Search resources",
        title: "Resources",
      },
      error: {
        archiveDownloadFallback:
          "Files remain available individually on the resource details page.",
        deleteUnauthorized: "You cannot delete this resource.",
        downloadAccess: "You do not have access to download this file.",
        downloadUnavailable:
          "A download link for {filename} could not be created. Try again.",
        editFailed: "We couldn't update this resource. Try again.",
        loadDetail: "We couldn't load this resource. Try again.",
        loadDirectory: "We couldn't load resources. Try again.",
        loadManagement: "We couldn't load your resources. Try again.",
        permanentDeleteUnauthorized:
          "Only an admin can permanently delete this resource.",
        previewAccess: "You do not have access to this preview image.",
        previewUnavailable:
          "A preview image link could not be created. Try again.",
        resourceNotFound: "Resource not found.",
        restoreUnauthorized: "You cannot restore this resource.",
        saveFailed: "We couldn't save this resource. Try again.",
      },
      management: {
        description: "Manage your uploads and publish new versions.",
        editDescription:
          "Update the resource details without replacing its uploaded files.",
        editResources: "Edit resources",
        editTitle: "Edit {name}",
        empty: "You haven't uploaded any resources yet.",
        metadataOnly:
          "To replace files, upload a new version. Existing versions stay available.",
        title: "Your resources",
      },
      moderation: {
        confirmationDescription:
          "Delist {name} from public Resources? The uploader and admins will still be able to view it.",
        confirmationTitle: "Mark resource private",
        failure: "We couldn't delist this resource. Try again.",
        privateBadge: "Delisted",
        privateReason: "Reason: {reason}",
        privateSince: "Delisted {date}",
        reasonLabel: "Reason for delisting",
        reasonPlaceholder: "Explain why this resource should be delisted",
        reasonRequired: "A reason is required.",
        success: "{name} is now delisted.",
      },
      notification: {
        acceptFailed: "We couldn't mark this notification as read. Try again.",
        accepted: "Notification marked as read.",
        categories: "Categories: {categories}",
        categoryCreated: "Category created",
        categoryName: "Category: {name}",
        createdAt: "Created {date}",
        description: "Review new resource and category activity.",
        empty: "No resource notifications.",
        read: "Read",
        resourceCreated: "Resource created",
        resourceName: "Resource: {name}",
        title: "Resource notifications",
        unread: "Unread",
        uploader: "Uploader: {uploader}",
      },
      trash: {
        adminEmpty: "No resources are in the trash.",
        adminTitle: "Resource trash",
        deletedBy: "Deleted by {user}",
        deletedOn: "Deleted {date}",
        deletionRoleAdmin: "Deleted by an admin",
        deletionRoleOwner: "Deleted by the owner",
        description:
          "Restore resources or permanently delete them from storage.",
        ownerEmpty: "You have no resources in the trash.",
        ownerTitle: "Your resource trash",
        permanentConfirmationDescription:
          "Permanently delete {name}? Every uploaded file, preview, version, and download record will be removed. This cannot be undone.",
        permanentConfirmationTitle: "Permanently delete resource",
        permanentFailure:
          "We couldn't permanently delete {name}. It remains in the trash and can be retried.",
        permanentSuccess: "{name} was permanently deleted.",
        restoreConfirmationDescription: "Restore {name} to Resources?",
        restoreConfirmationTitle: "Restore resource",
        restoreFailure: "We couldn't restore {name}. Try again.",
        restoreSuccess: "{name} was restored.",
        softDeleteConfirmationDescription:
          "Move {name} to the trash? It will no longer appear in Resources or be available to download.",
        softDeleteConfirmationTitle: "Move resource to trash",
        softDeleteFailure: "We couldn't move {name} to the trash. Try again.",
        softDeleteSuccess: "{name} was moved to the trash.",
      },
      upload: {
        browseFiles: "Browse",
        description:
          "Share files with the Pocket Trash community. All fields are required.",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Describe this resource",
        expired: "This upload session expired. Start the upload again.",
        fileFailure: "{filename} couldn't be uploaded. Retry this file.",
        fileHelp:
          "Choose 1–{maxFiles} files. Each file can be up to {maxFileSize}; the complete upload can be up to {maxSessionSize}.",
        fileTypes:
          "Allowed file types: STL, 3MF, STEP, STP, PDF, TXT, ZIP, JPEG, PNG, WebP, and AVIF.",
        filesLabel: "Resource files",
        finalizationFailure:
          "Your files were uploaded, but the resource could not be finalized. Retry to finish the upload.",
        finalizing: "Finishing your upload…",
        imagesHelp:
          "Choose 1–{maxImages} images. The first image is the cover. Each image can be up to {maxFileSize}; all files in this upload can total up to {maxSessionSize}.",
        imagesLabel: "Images",
        imageTypes: "Allowed image types: JPEG, PNG, WebP, and AVIF.",
        nameLabel: "Name",
        namePlaceholder: "Resource name",
        newVersionTitle: "Upload a new version of {name}",
        previewHelp: "Optional image shown in resource cards and details.",
        previewLabel: "Preview image",
        previewTypes: "Allowed preview types: JPEG, PNG, WebP, and AVIF.",
        progress: "Uploading {filename}: {percent}%",
        retryFile: "Retry {filename}",
        sessionFailure: "We couldn't start the upload. Try again.",
        success: "Your resource was added.",
        title: "Add Resource",
        versionSuccess: "Version {version} was uploaded.",
      },
      validation: {
        duplicateFilename: "Remove the duplicate filename {filename}.",
        fileTooLarge: "{filename} must be {maxSize} or smaller.",
        imageInvalidType: "Choose a supported image type.",
        imageTooLarge: "Each image must be {maxSize} or smaller.",
        invalidFileType: "{filename} is not an allowed file type.",
        previewInvalidType: "Choose a supported preview image type.",
        previewTooLarge: "The preview image must be {maxSize} or smaller.",
        requiredCategory: "Select at least one category.",
        requiredDescription: "Enter a description.",
        requiredFile: "Choose at least one resource file.",
        requiredImage: "Choose at least one image.",
        requiredName: "Enter a resource name.",
        sessionTooLarge: "The complete upload must be {maxSize} or smaller.",
        tooManyFiles: "Choose no more than {maxFiles} resource files.",
        tooManyImages: "Choose no more than {maxImages} images.",
        unsafeFilename: "Rename {filename} before uploading it.",
      },
      visibility: {
        adminPrivateTooltip:
          "An administrator marked this resource private. Only an administrator can make it public.",
        private: "Private",
        public: "Public",
      },
    },
    settings: {
      about: "About",
      aboutDescription:
        "An unofficial archive of machined pen drops, with filters, specs, descriptions, and local image backups. Made by a fan; not affiliated with any maker.",
      currency: "Currency",
      dark: "Dark",
      dimensionUnits: "Dimension units",
      dimensions: "Dimensions",
      displayCurrency: "Display currency",
      displayPreferences: "Display preferences for the archive.",
      displayPreferencesMachinedPens: "Display preferences for Pocket Trash.",
      grams: "Grams",
      inches: "Inches",
      imperial: "Imperial",
      language: "Language",
      light: "Light",
      measurementSystem: "Measurement system options",
      measurementSystemLabel: "Measurement system",
      metric: "Metric",
      millimeters: "Millimeters",
      settings: "Settings",
      system: "System",
      theme: "Theme",
      weight: "Weight",
      weightUnits: "Weight units",
      ounces: "Ounces",
    },
    sidebar: {
      adminMenu: "Admin Menu",
      close: "Close sidebar",
      description: "Displays the mobile sidebar.",
      profile: "Profile",
      sidebar: "Sidebar",
      toggle: "Toggle sidebar",
    },
    status: {
      disabled: "Disabled",
      enabled: "Enabled",
      failedToLoad: "Failed to load.",
    },
    storage: {
      sizeMiB: "{value} MiB",
    },
    upload: {
      finalizationFailure:
        "Your files were uploaded, but the upload could not be finalized. Try again.",
      saveFailed: "We couldn't save your upload. Try again.",
    },
  },
} satisfies CompleteLocalizationResource;
