import type { CompleteLocalizationResource } from "../types/localization.js";

/**
 * English (United States) translations for Pocket Trash.
 *
 * This catalog is checked against `CompleteLocalizationResource` from
 * `src/types/localization.ts`. When adding a translation key, update that type
 * first, then add the required English string here. Other locale catalogs can
 * omit most new keys until a translation is available; omitted keys fall back to
 * this `en-US` catalog at runtime.
 */
export const enUS = {
  app: {
    name: "Pocket Trash",
  },
  action: {
    cancel: "Cancel",
    save: "Save",
  },
  error: {
    generic: "Something went wrong.",
  },
  locale: {
    current: "Current language: {locale}",
  },
  web: {
    site: {
      name: "Pocket Trash",
    },
    action: {
      addCollection: "Add collection",
      addColor: "Add colour",
      addFinish: "Add finish",
      addFinishOption: "Add finish option",
      addMaker: "Add maker",
      addMaterial: "Add material",
      addProduct: "Add product",
      addToCollection: "Add to collection",
      archive: "Archive",
      clearAllFilters: "Clear all filters",
      clearCover: "Clear cover",
      close: "Close",
      confirmAdd: "Add another",
      deleteCover: "Delete cover",
      edit: "Edit",
      more: "More",
      moreFilters: "More filters",
      moveFinishOptionDown: "Move finish option down",
      moveFinishOptionUp: "Move finish option up",
      removeFinishOption: "Remove finish option",
      removeSelection: "Remove {name}",
      saveFlag: "Save flag",
      search: "Search",
      selectCover: "Use this cover",
      signIn: "Sign in",
      visitProductPage: "Visit product page",
    },
    admin: {
      featureFlags: {
        actions: "Actions",
        adminOnlyTargeting: "Admin-only targeting",
        audience: "Audience",
        booleanControls:
          "Boolean controls for global, private, and beta surfaces.",
        description: "Description",
        displayName: "Display name",
        editFlag: "Edit flag",
        emailUsernameOrName: "Email, username, or name",
        featureFlags: "Feature flags",
        flag: "Flag",
        flags: "Flags",
        globalDefaultEnabled: "Global default enabled",
        newFlag: "New flag",
        searchUsers: "Search users",
        slugPlaceholder: "new-library-ui",
      },
    },
    archive: {
      closeSearch: "Close search",
      controls: "Archive controls",
      defaultPenDescription: "{siteName} pen.",
      filterDescription:
        "Filter the archive by category, size, material, and more.",
      filters: "Filters",
      itemCount: "{visible} of {total} items",
      noDescription: "(no description on file)",
      noItems: "No items match these filters.",
      searchPlaceholder: "Search...",
      searchProducts: "Search pens by title, specs, or description",
      sortLabel: "Sort",
      sortProducts: "Sort pens",
      sortDescription: "Choose how the archive is ordered.",
      footer: {
        fanMade: "Made by a fan; not affiliated with any maker.",
        productOwnership:
          "Product names, images, and descriptions remain the property of their respective owners.",
        resourceFor: "A resource for",
        suggestionsOrContact: "Suggestions or contact:",
        discord: "and the Machined Pens Discord.",
      },
      headline: {
        grip: "{size} Grip",
        mechanism: "{size} Mechanism",
        pen: "Pen",
      },
      lightbox: {
        archived: "Archived - no longer listed",
        closeProductDetails: "Close product details",
        nextImage: "Next image",
        previousImage: "Previous image",
        released: "Released",
        specsDescription:
          "Specs, materials, and release details for this product.",
      },
      filter: {
        all: "all",
        any: "any",
        matchMode: "{label} match mode",
        bodyDetails: "Body details",
        category: "Category",
        clip: "Clip",
        finish: "Finish",
        material: "Material",
        mechanism: "Mechanism",
        refill: "Refill",
        size: "Size",
        tipNose: "Tip / Nose",
      },
      sort: {
        newestDrop: "Newest drop",
        oldestDrop: "Oldest drop",
        priceLowToHigh: "Price low to high",
        priceHighToLow: "Price high to low",
        weightLightToHeavy: "Weight light to heavy",
        weightHeavyToLight: "Weight heavy to light",
        diameterThinToThick: "Diameter thin to thick",
        diameterThickToThin: "Diameter thick to thin",
        titleAToZ: "Title A to Z",
      },
      spec: {
        diameter: "Diameter",
        length: "Length",
        model: "Model",
        price: "Price",
        weight: "Weight",
      },
      state: {
        archived: "Archived",
      },
    },
    catalog: {
      colorEffect: {
        fade: "Fade",
        solid: "Solid",
      },
      defaultButton: "Default Button",
      error: {
        colorHex: "Choose a valid colour.",
        colorEffectRequired: "Select a colour effect.",
        colorEffectWithoutColors: "Add a colour or remove the colour effect.",
        duplicate: "That name already exists.",
        duplicateComponent: "Each finish or colour can only be selected once.",
        duplicateFinishOption: "That finish option is already listed.",
        fadeColors: "Select at least two colours for a fade.",
        finishOptionRequired: "Add at least one finish option.",
        finishRequired: "Select at least one finish.",
        form: "We couldn't save this. Check the fields and try again.",
        positive: "Enter a number greater than zero.",
        productFinishRequired:
          "Select a product finish or create a custom finish.",
        productMaterialRequired: "Select a material offered by this product.",
        required: "This field is required.",
        url: "Enter a valid URL.",
      },
      field: {
        button: "Button",
        buttonDiameter: "Button diameter",
        colorEffect: "Colour effect",
        colorValue: "Colour value",
        colors: "Colours",
        finishes: "Finishes",
        finishOptions: "Finish options",
        maker: "Maker",
        materials: "Materials",
        name: "Name",
        productType: "Product type",
        rootUrl: "Maker URL",
        slug: "Slug",
        thickness: "Thickness",
        thicknessWithButton: "Thickness with button",
        width: "Width",
      },
      filter: {
        description:
          "Filter by product type, material, finish, colour, and maker.",
        fadeName: "{colors} fade",
        moreOptions: "More {label}",
        productTypeAll: "All product types",
      },
      finishOptionCount: "Finish options: {count}",
      finishPreview: "Preview: {finish}",
      materialCount: "Materials: {count}",
      noProducts: "No products yet.",
      notImplemented: "This product type is not implemented yet.",
      selectColorEffect: "Select a colour effect",
      selectColors: "Select colours",
      selectFinishes: "Select finishes",
      selectFinishOption: "Select a finish option",
      selectMaker: "Select a maker",
      selectMaterial: "Select a material",
      selectMaterials: "Select materials",
      selectProductType: "Select a product type",
    },
    collections: {
      add: {
        title: "Add collection",
      },
      cover: {
        clearConfirmation:
          "Clear the current cover? It will remain available under previous covers.",
        current: "Current cover",
        deleteConfirmation:
          "Permanently delete this cover image? This cannot be undone.",
        history: "Previous covers",
      },
      directory: {
        avatar: "Generic collector avatar",
        itemCount: "Collection items: {count}",
        matchingItemCount: "{matching} of {total} collection items",
      },
      duplicateWarning:
        "Matching products already owned: {count}. Confirm to add another.",
      edit: {
        noFields:
          "There are no collection-specific fields to edit for this item.",
        title: "Edit collection",
      },
      empty: "No collection items yet.",
      emptyCollections: "You don't have any collections yet.",
      error: {
        chooseCollection: "Choose a collection.",
        syncIncomplete: "Your profile is still syncing. Try again.",
        upload:
          "The collection was saved, but its cover could not be uploaded. Try again from Edit collection.",
      },
      field: {
        collection: "Collection",
        cover: "Cover image",
        description: "Description",
        name: "Name",
      },
      finishChoice: {
        custom: "Custom finish",
        product: "Product finish",
      },
      placeholder: {
        description: "Describe this collection",
        name: "Collection name",
      },
      select: {
        addNew: "Add new collection",
        placeholder: "Select a collection",
      },
      visibility: {
        privateCallout:
          "This item is public, but it will remain hidden while its collection is private.",
      },
    },
    currency: {
      aud: "$ AUD",
      cad: "$ CAD (native)",
      chf: "CHF",
      eur: "EUR EUR",
      gbp: "GBP GBP",
      jpy: "JPY JPY",
      nzd: "$ NZD",
      usd: "$ USD",
    },
    error: {
      expectedJsonRequestBody: "Expected a JSON request body.",
      invalidCurrencyCode: "Expected a valid currency code.",
      invalidDimensionUnit: "Expected a valid dimension unit.",
      invalidLocale: "Expected a valid locale.",
      invalidLogClientKey: "Invalid log client key.",
      invalidTheme: "Expected a valid theme.",
      invalidWeightUnit: "Expected a valid weight unit.",
      missingSetting: "Expected at least one setting.",
      settingsSaveFailed: "We couldn't save your settings. Please try again.",
      userSettingsObject: "Expected a user settings object.",
    },
    navigation: {
      account: "Account",
      accountMenu: "Account menu",
      betaFeatures: "Beta features",
      collections: "Collections",
      language: "Language",
      logOut: "Log out",
      products: "Products",
      resources: "Resources",
      selectLanguage: "Select language",
      user: "User",
    },
    locale: {
      enUS: "English (US)",
      esMX: "Spanish (Mexico)",
    },
    page: {
      betaFeatures: {
        empty: "No beta features are available.",
      },
      collections: {
        empty: "Collections will be available later.",
      },
      notFound: {
        description: "This page does not exist or is no longer available.",
        returnToArchive: "Return to archive",
        title: "Not found",
        unavailable: "Page unavailable",
      },
      resources: {
        stub: "Resources are coming soon.",
      },
    },
    resources: {
      action: {
        accept: "Accept",
        add: "Add Resource",
        closeImage: "Close image",
        collapseVersion: "Collapse version {version}",
        collapseVersionHistory: "Collapse version history",
        delete: "Move to trash",
        details: "Details",
        download: "Download",
        edit: "Edit",
        expandVersion: "Expand version {version}",
        expandVersionHistory: "Expand version history",
        markPrivate: "Mark private",
        nextImage: "Next image",
        permanentlyDelete: "Delete permanently",
        previousImage: "Previous image",
        removeFile: "Remove file",
        restore: "Restore",
        retry: "Retry",
        saveChanges: "Save changes",
        upload: "Add Resource",
        uploadNewVersion: "Upload new version",
      },
      add: {
        title: "Add Resource",
      },
      category: {
        all: "All categories",
        create: "Create “{category}”",
        filterLabel: "Filter by category",
        label: "Categories",
        noResults: "No categories found.",
        remove: "Remove {category}",
        search: "Search categories",
        select: "Select one or more categories",
        selectedCount: "Selected categories: {count}",
      },
      detail: {
        categories: "Categories",
        currentVersion: "Current version",
        downloadCount: "Downloads: {count}",
        fileSize: "Size: {size}",
        fileTypeFallback: "File",
        filename: "File: {filename}",
        imageAlt: "Image of {name}",
        noImage: "No image available",
        noPreview: "No preview image",
        notFound: "This resource is not available.",
        openImage: "Open {name}",
        previewAlt: "Preview of {name}",
        sharedBy: "Shared by",
        totalDownloadCount: "Total downloads: {count}",
        updatedOn: "Updated {date}",
        uploadedBy: "Uploaded by {uploader}",
        uploadedOn: "Uploaded {date}",
        version: "Version {version}",
        versionHistory: "Version history",
        versionUploadedOn: "Version {version}, uploaded {date}",
      },
      directory: {
        description: "Browse files shared by the Pocket Trash community.",
        empty: "No resources have been uploaded yet.",
        emptyFiltered: "No resources match these category filters.",
        filters: "Resource filters",
        invalidFilter: "One or more category filters are invalid.",
        loading: "Loading resources…",
        searchPlaceholder: "Search resources",
        title: "Resources",
      },
      error: {
        deleteUnauthorized: "You cannot delete this resource.",
        downloadAccess: "You do not have access to download this file.",
        downloadUnavailable:
          "A download link for {filename} could not be created. Try again.",
        editFailed: "We couldn't update this resource. Try again.",
        loadDetail: "We couldn't load this resource. Try again.",
        loadDirectory: "We couldn't load resources. Try again.",
        loadManagement: "We couldn't load your resources. Try again.",
        permanentDeleteUnauthorized:
          "Only an admin can permanently delete this resource.",
        previewAccess: "You do not have access to this preview image.",
        previewUnavailable:
          "A preview image link could not be created. Try again.",
        resourceNotFound: "Resource not found.",
        restoreUnauthorized: "You cannot restore this resource.",
        saveFailed: "We couldn't save this resource. Try again.",
      },
      management: {
        description: "Manage your uploads and publish new versions.",
        editDescription:
          "Update the resource details without replacing its uploaded files.",
        editResources: "Edit resources",
        editTitle: "Edit {name}",
        empty: "You haven't uploaded any resources yet.",
        metadataOnly:
          "To replace files, upload a new version. Existing versions stay available.",
        title: "Your resources",
      },
      moderation: {
        confirmationDescription:
          "Delist {name} from public Resources? The uploader and admins will still be able to view it.",
        confirmationTitle: "Mark resource private",
        failure: "We couldn't delist this resource. Try again.",
        privateBadge: "Delisted",
        privateReason: "Reason: {reason}",
        privateSince: "Delisted {date}",
        reasonLabel: "Reason for delisting",
        reasonPlaceholder: "Explain why this resource should be delisted",
        reasonRequired: "A reason is required.",
        success: "{name} is now delisted.",
      },
      notification: {
        acceptFailed: "We couldn't mark this notification as read. Try again.",
        accepted: "Notification marked as read.",
        categories: "Categories: {categories}",
        categoryCreated: "Category created",
        categoryName: "Category: {name}",
        createdAt: "Created {date}",
        description: "Review new resource and category activity.",
        empty: "No resource notifications.",
        read: "Read",
        resourceCreated: "Resource created",
        resourceName: "Resource: {name}",
        title: "Resource notifications",
        unread: "Unread",
        uploader: "Uploader: {uploader}",
      },
      trash: {
        adminEmpty: "No resources are in the trash.",
        adminTitle: "Resource trash",
        deletedBy: "Deleted by {user}",
        deletedOn: "Deleted {date}",
        deletionRoleAdmin: "Deleted by an admin",
        deletionRoleOwner: "Deleted by the owner",
        description:
          "Restore resources or permanently delete them from storage.",
        ownerEmpty: "You have no resources in the trash.",
        ownerTitle: "Your resource trash",
        permanentConfirmationDescription:
          "Permanently delete {name}? Every uploaded file, preview, version, and download record will be removed. This cannot be undone.",
        permanentConfirmationTitle: "Permanently delete resource",
        permanentFailure:
          "We couldn't permanently delete {name}. It remains in the trash and can be retried.",
        permanentSuccess: "{name} was permanently deleted.",
        restoreConfirmationDescription: "Restore {name} to Resources?",
        restoreConfirmationTitle: "Restore resource",
        restoreFailure: "We couldn't restore {name}. Try again.",
        restoreSuccess: "{name} was restored.",
        softDeleteConfirmationDescription:
          "Move {name} to the trash? It will no longer appear in Resources or be available to download.",
        softDeleteConfirmationTitle: "Move resource to trash",
        softDeleteFailure: "We couldn't move {name} to the trash. Try again.",
        softDeleteSuccess: "{name} was moved to the trash.",
      },
      upload: {
        browseFiles: "Browse",
        description:
          "Share files with the Pocket Trash community. All fields are required.",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Describe this resource",
        expired: "This upload session expired. Start the upload again.",
        fileFailure: "{filename} couldn't be uploaded. Retry this file.",
        fileHelp:
          "Choose 1–{maxFiles} files. Each file can be up to {maxFileSize}; the complete upload can be up to {maxSessionSize}.",
        fileTypes:
          "Allowed file types: STL, 3MF, STEP, STP, PDF, TXT, and ZIP.",
        filesLabel: "Resource files",
        finalizationFailure:
          "Your files were uploaded, but the resource could not be finalized. Retry to finish the upload.",
        finalizing: "Finishing your upload…",
        imagesHelp:
          "Choose 1–{maxImages} images. The first image is the cover. Each image can be up to {maxFileSize}; all files in this upload can total up to {maxSessionSize}.",
        imagesLabel: "Images",
        imageTypes: "Allowed image types: JPEG, PNG, and WebP.",
        nameLabel: "Name",
        namePlaceholder: "Resource name",
        newVersionTitle: "Upload a new version of {name}",
        previewHelp: "Optional image shown in resource cards and details.",
        previewLabel: "Preview image",
        previewTypes: "Allowed preview types: JPEG, PNG, and WebP.",
        progress: "Uploading {filename}: {percent}%",
        retryFile: "Retry {filename}",
        sessionFailure: "We couldn't start the upload. Try again.",
        success: "Your resource was added.",
        title: "Add Resource",
        versionSuccess: "Version {version} was uploaded.",
      },
      validation: {
        duplicateFilename: "Remove the duplicate filename {filename}.",
        fileTooLarge: "{filename} must be {maxSize} or smaller.",
        imageInvalidType: "Choose a supported image type.",
        imageTooLarge: "Each image must be {maxSize} or smaller.",
        invalidFileType: "{filename} is not an allowed file type.",
        previewInvalidType: "Choose a supported preview image type.",
        previewTooLarge: "The preview image must be {maxSize} or smaller.",
        requiredCategory: "Select at least one category.",
        requiredDescription: "Enter a description.",
        requiredFile: "Choose at least one resource file.",
        requiredImage: "Choose at least one image.",
        requiredName: "Enter a resource name.",
        sessionTooLarge: "The complete upload must be {maxSize} or smaller.",
        tooManyFiles: "Choose no more than {maxFiles} resource files.",
        tooManyImages: "Choose no more than {maxImages} images.",
        unsafeFilename: "Rename {filename} before uploading it.",
      },
      visibility: {
        adminPrivateTooltip:
          "An administrator marked this resource private. Only an administrator can make it public.",
        private: "Private",
        public: "Public",
      },
    },
    settings: {
      about: "About",
      aboutDescription:
        "An unofficial archive of machined pen drops, with filters, specs, descriptions, and local image backups. Made by a fan; not affiliated with any maker.",
      currency: "Currency",
      dark: "Dark",
      dimensionUnits: "Dimension units",
      dimensions: "Dimensions",
      displayCurrency: "Display currency",
      displayPreferences: "Display preferences for the archive.",
      displayPreferencesMachinedPens: "Display preferences for Pocket Trash.",
      grams: "Grams",
      inches: "Inches",
      language: "Language",
      light: "Light",
      millimeters: "Millimeters",
      settings: "Settings",
      system: "System",
      theme: "Theme",
      weight: "Weight",
      weightUnits: "Weight units",
      ounces: "Ounces",
    },
    sidebar: {
      close: "Close sidebar",
      description: "Displays the mobile sidebar.",
      sidebar: "Sidebar",
      toggle: "Toggle sidebar",
    },
    status: {
      disabled: "Disabled",
      enabled: "Enabled",
      failedToLoad: "Failed to load.",
    },
  },
} satisfies CompleteLocalizationResource;
