import type { LocalizationResource } from "../types/localization.js";

/**
 * es-MX translations for Pocket Trash.
 *
 * This catalog is checked against `LocalizationResource` from
 * `src/types/localization.ts`. When adding a translation key, update that type
 * first, add the required English string in `src/localizations/en-US.ts`, then
 * run `pnpm localization:sync` so this locale gets any missing blank fields.
 * Blank strings fall back to `en-US` at runtime until translated.
 */
export const esMX = {
  app: {
    name: "",
  },
  action: {
    cancel: "Cancelar",
    save: "Guardar",
  },
  error: {
    generic: "Algo salio mal.",
  },
  locale: {
    current: "Idioma actual: {locale}",
  },
  web: {
    site: {
      name: "",
    },
    action: {
      addCollection: "",
      addColor: "Agregar color",
      addFinish: "Agregar acabado",
      addFinishOption: "Agregar opción de acabado",
      addMaker: "",
      addMaterial: "",
      addProduct: "",
      addToCollection: "",
      archive: "Archivar",
      clearAllFilters: "Borrar todos los filtros",
      clearCover: "",
      close: "Cerrar",
      confirmAdd: "",
      deleteCover: "",
      edit: "Editar",
      more: "Más",
      moreFilters: "Más filtros",
      moveFinishOptionDown: "Mover la opción de acabado hacia abajo",
      moveFinishOptionUp: "Mover la opción de acabado hacia arriba",
      removeFinishOption: "Quitar opción de acabado",
      removeSelection: "Quitar {name}",
      saveFlag: "Guardar bandera",
      search: "Buscar",
      selectCover: "",
      signIn: "Iniciar sesion",
      view: "Ver",
      viewCollection: "Ver colección",
      viewItem: "Ver artículo",
      viewProductDetails: "Ver detalles del producto",
      visitProductPage: "Visitar pagina del producto",
    },
    admin: {
      featureFlags: {
        actions: "Acciones",
        adminOnlyTargeting: "Segmentacion solo para admins",
        audience: "Audiencia",
        booleanControls:
          "Controles booleanos para superficies globales, privadas y beta.",
        description: "Descripcion",
        displayName: "Nombre visible",
        editFlag: "Editar bandera",
        emailUsernameOrName: "Email, usuario o nombre",
        featureFlags: "Banderas de funciones",
        flag: "Bandera",
        flags: "Banderas",
        globalDefaultEnabled: "Valor global activado",
        newFlag: "Nueva bandera",
        searchUsers: "Buscar usuarios",
        slugPlaceholder: "",
      },
    },
    archive: {
      closeSearch: "Cerrar busqueda",
      controls: "Controles del archivo",
      defaultPenDescription: "",
      filterDescription:
        "Filtra el archivo por categoria, tamano, material y mas.",
      filters: "Filtros",
      itemCount: "",
      noDescription: "",
      noItems: "Ningun articulo coincide con estos filtros.",
      searchPlaceholder: "Buscar...",
      searchProducts:
        "Buscar plumas por titulo, especificaciones o descripcion",
      sortLabel: "Ordenar",
      sortProducts: "Ordenar plumas",
      sortDescription: "Elige como ordenar el archivo.",
      footer: {
        fanMade: "Hecho por un fan; sin afiliacion con ningun fabricante.",
        productOwnership:
          "Los nombres, imagenes y descripciones de productos siguen siendo propiedad de sus respectivos duenos.",
        resourceFor: "Un recurso para",
        suggestionsOrContact: "Sugerencias o contacto:",
        discord: "y el Discord de Machined Pens.",
      },
      headline: {
        grip: "",
        mechanism: "",
        pen: "",
      },
      lightbox: {
        archived: "Archivada - ya no esta listada",
        closeProductDetails: "Cerrar detalles del producto",
        nextImage: "Siguiente imagen",
        previousImage: "Imagen anterior",
        released: "Publicado",
        specsDescription:
          "Especificaciones, materiales y detalles de lanzamiento de este producto.",
      },
      filter: {
        all: "todos",
        any: "cualquiera",
        matchMode: "Modo de coincidencia de {label}",
        bodyDetails: "",
        category: "",
        clip: "",
        finish: "",
        material: "",
        mechanism: "",
        refill: "",
        size: "",
        tipNose: "",
      },
      sort: {
        newestDrop: "Lanzamiento mas reciente",
        oldestDrop: "Lanzamiento mas antiguo",
        priceLowToHigh: "Precio de menor a mayor",
        priceHighToLow: "Precio de mayor a menor",
        weightLightToHeavy: "Peso de menor a mayor",
        weightHeavyToLight: "Peso de mayor a menor",
        diameterThinToThick: "Diametro de delgado a grueso",
        diameterThickToThin: "Diametro de grueso a delgado",
        titleAToZ: "Titulo A a Z",
      },
      spec: {
        diameter: "Diametro",
        length: "Longitud",
        model: "Modelo",
        price: "Precio",
        weight: "Peso",
      },
      state: {
        archived: "Archivada",
      },
    },
    catalog: {
      collectionsWithProduct: "Colecciones con este producto",
      colorEffect: {
        fade: "Degradado",
        solid: "Sólido",
      },
      defaultButton: "",
      error: {
        bearingLength: "",
        colorHex: "Elige un color válido.",
        colorEffectRequired: "Selecciona un efecto de color.",
        colorEffectWithoutColors: "Agrega un color o quita el efecto de color.",
        descriptionLength: "",
        duplicate: "",
        duplicateComponent:
          "Cada acabado o color solo puede seleccionarse una vez.",
        duplicateFinishOption: "Esa opción de acabado ya está en la lista.",
        fadeColors: "Selecciona al menos dos colores para un degradado.",
        finishOptionRequired: "Agrega al menos una opción de acabado.",
        finishRequired: "Selecciona al menos un acabado.",
        form: "",
        positive: "",
        productFinishRequired:
          "Selecciona un acabado del producto o crea un acabado personalizado.",
        productMaterialRequired:
          "Selecciona un material ofrecido por este producto.",
        required: "",
        url: "",
      },
      field: {
        bearing: "",
        button: "",
        buttonDiameter: "",
        colorEffect: "Efecto de color",
        colorValue: "Valor del color",
        colors: "Colores",
        description: "",
        finishes: "Acabados",
        finishOptions: "Opciones de acabado",
        maker: "",
        makerProductUrl: "",
        materials: "",
        name: "",
        productType: "",
        rootUrl: "",
        slug: "",
        spinDiameter: "",
        thickness: "",
        thicknessWithButton: "",
        width: "",
      },
      filter: {
        description:
          "Filtra por tipo de producto, material, acabado, color y fabricante.",
        fadeName: "Degradado {colors}",
        moreOptions: "Más opciones de {label}",
        productTypeAll: "Todos los tipos de producto",
      },
      help: {
        collectionDescriptionOverride: "",
        makerProductUrl: "",
        markdownDescription: "",
      },
      images: {
        aspectRatioGuideLink: "Leer la guía de tamaño y resolución de imágenes",
        aspectRatioWarning:
          "Esta imagen no tiene una relación de aspecto de 4:3 y se recortará al mostrarse.",
      },
      finishOptionCount: "Opciones de acabado: {count}",
      finishPreview: "Vista previa: {finish}",
      materialCount: "Materiales: {count}",
      noProducts: "",
      notImplemented: "",
      selectColorEffect: "Selecciona un efecto de color",
      selectColors: "Selecciona colores",
      selectFinishes: "Selecciona acabados",
      selectFinishOption: "Selecciona una opción de acabado",
      selectMaker: "",
      selectMaterial: "Selecciona un material",
      selectMaterials: "",
      selectProductType: "",
    },
    collections: {
      add: {
        title: "",
      },
      cover: {
        clearConfirmation: "",
        current: "",
        deleteConfirmation: "",
        history: "",
      },
      directory: {
        avatar: "",
        itemCount: "",
        matchingItemCount: "{matching} de {total} artículos de la colección",
      },
      duplicateWarning: "",
      edit: {
        noFields: "",
        title: "",
      },
      empty: "",
      emptyCollections: "",
      error: {
        chooseCollection: "",
        syncIncomplete: "",
        upload: "",
      },
      field: {
        collection: "",
        cover: "",
        description: "",
        displayName: "Nombre para mostrar",
        name: "",
      },
      finishChoice: {
        custom: "Acabado personalizado",
        product: "Acabado del producto",
      },
      placeholder: {
        description: "",
        name: "",
      },
      select: {
        addNew: "",
        placeholder: "",
      },
      visibility: {
        privateCallout: "",
      },
    },
    currency: {
      aud: "",
      cad: "",
      chf: "",
      eur: "",
      gbp: "",
      jpy: "",
      nzd: "",
      usd: "",
    },
    error: {
      expectedJsonRequestBody: "",
      invalidCurrencyCode: "",
      invalidDimensionUnit: "",
      invalidLocale: "",
      invalidLogClientKey: "",
      invalidTheme: "",
      invalidWeightUnit: "",
      missingSetting: "",
      settingsSaveFailed: "",
      userSettingsObject: "",
    },
    help: {
      comingSoon: "Próximamente.",
      contact: "Contacto",
      dateModified: "Fecha de modificación",
      datePublished: "Fecha",
      developmentCallout: "Esta página todavía está en desarrollo.",
      topics: "Temas de ayuda",
    },
    navigation: {
      account: "Cuenta",
      accountMenu: "Menu de cuenta",
      betaFeatures: "Funciones beta",
      collections: "Colecciones",
      help: "Ayuda",
      language: "Idioma",
      logOut: "Cerrar sesion",
      products: "",
      resources: "",
      selectLanguage: "Seleccionar idioma",
      user: "Usuario",
    },
    locale: {
      enUS: "",
      esMX: "",
    },
    page: {
      betaFeatures: {
        empty: "No hay funciones beta disponibles.",
      },
      collections: {
        empty: "Las colecciones estaran disponibles mas adelante.",
      },
      notFound: {
        description: "Esta pagina no existe o ya no esta disponible.",
        returnToArchive: "Volver al archivo",
        title: "No encontrado",
        unavailable: "Pagina no disponible",
      },
      resources: {
        stub: "",
      },
    },
    resources: {
      action: {
        accept: "Aceptar",
        add: "Agregar recurso",
        closeImage: "Cerrar imagen",
        collapseVersion: "Contraer la versión {version}",
        collapseVersionHistory: "Contraer el historial de versiones",
        delete: "Mover a la papelera",
        details: "Detalles",
        download: "Descargar",
        edit: "Editar",
        expandVersion: "Expandir la versión {version}",
        expandVersionHistory: "Expandir el historial de versiones",
        markPrivate: "Marcar como privado",
        nextImage: "Imagen siguiente",
        permanentlyDelete: "Eliminar permanentemente",
        previousImage: "Imagen anterior",
        removeFile: "Quitar archivo",
        restore: "Restaurar",
        retry: "Reintentar",
        saveChanges: "Guardar cambios",
        upload: "Agregar recurso",
        uploadNewVersion: "Subir nueva versión",
      },
      add: {
        title: "Agregar recurso",
      },
      category: {
        all: "Todas las categorías",
        create: "Crear “{category}”",
        filterLabel: "Filtrar por categoría",
        label: "Categorías",
        noResults: "No se encontraron categorías.",
        remove: "Quitar {category}",
        search: "Buscar categorías",
        select: "Selecciona una o más categorías",
        selectedCount: "Categorías seleccionadas: {count}",
      },
      detail: {
        categories: "Categorías",
        currentVersion: "Versión actual",
        downloadCount: "Descargas: {count}",
        fileSize: "Tamaño: {size}",
        fileTypeFallback: "Archivo",
        filename: "Archivo: {filename}",
        imageAlt: "Imagen de {name}",
        noImage: "No hay imagen disponible",
        noPreview: "Sin imagen de vista previa",
        notFound: "Este recurso no está disponible.",
        openImage: "Abrir {name}",
        previewAlt: "Vista previa de {name}",
        sharedBy: "Compartido por",
        totalDownloadCount: "Descargas totales: {count}",
        updatedOn: "Actualizado el {date}",
        uploadedBy: "Subido por {uploader}",
        uploadedOn: "Subido el {date}",
        version: "Versión {version}",
        versionHistory: "Historial de versiones",
        versionUploadedOn: "Versión {version}, subida el {date}",
      },
      directory: {
        description:
          "Explora archivos compartidos por la comunidad de Pocket Trash.",
        empty: "Todavía no se han subido recursos.",
        emptyFiltered:
          "Ningún recurso coincide con estos filtros de categoría.",
        filters: "Filtros de recursos",
        invalidFilter: "Uno o más filtros de categoría no son válidos.",
        loading: "Cargando recursos…",
        searchPlaceholder: "Buscar recursos",
        title: "Recursos",
      },
      error: {
        deleteUnauthorized: "No puedes eliminar este recurso.",
        downloadAccess: "No tienes acceso para descargar este archivo.",
        downloadUnavailable:
          "No se pudo crear un enlace de descarga para {filename}. Inténtalo de nuevo.",
        editFailed: "No pudimos actualizar este recurso. Inténtalo de nuevo.",
        loadDetail: "No pudimos cargar este recurso. Inténtalo de nuevo.",
        loadDirectory: "No pudimos cargar los recursos. Inténtalo de nuevo.",
        loadManagement: "No pudimos cargar tus recursos. Inténtalo de nuevo.",
        permanentDeleteUnauthorized:
          "Solo un administrador puede eliminar este recurso permanentemente.",
        previewAccess: "No tienes acceso a esta imagen de vista previa.",
        previewUnavailable:
          "No se pudo crear un enlace para la imagen de vista previa. Inténtalo de nuevo.",
        resourceNotFound: "Recurso no encontrado.",
        restoreUnauthorized: "No puedes restaurar este recurso.",
        saveFailed: "No pudimos guardar este recurso. Inténtalo de nuevo.",
      },
      management: {
        description: "Administra tus cargas y publica nuevas versiones.",
        editDescription:
          "Actualiza los detalles del recurso sin reemplazar los archivos subidos.",
        editResources: "Editar recursos",
        editTitle: "Editar {name}",
        empty: "Todavía no has subido ningún recurso.",
        metadataOnly:
          "Para reemplazar archivos, sube una nueva versión. Las versiones anteriores seguirán disponibles.",
        title: "Tus recursos",
      },
      moderation: {
        confirmationDescription:
          "¿Quieres retirar {name} de Recursos? La persona que lo subió y los administradores aún podrán verlo.",
        confirmationTitle: "Marcar recurso como privado",
        failure: "No pudimos retirar este recurso. Inténtalo de nuevo.",
        privateBadge: "Retirado",
        privateReason: "Motivo: {reason}",
        privateSince: "Retirado el {date}",
        reasonLabel: "Motivo del retiro",
        reasonPlaceholder: "Explica por qué se debe retirar este recurso",
        reasonRequired: "Se requiere un motivo.",
        success: "{name} ahora está retirado.",
      },
      notification: {
        acceptFailed:
          "No pudimos marcar esta notificación como leída. Inténtalo de nuevo.",
        accepted: "Notificación marcada como leída.",
        categories: "Categorías: {categories}",
        categoryCreated: "Categoría creada",
        categoryName: "Categoría: {name}",
        createdAt: "Creada el {date}",
        description: "Revisa la actividad nueva de recursos y categorías.",
        empty: "No hay notificaciones de recursos.",
        read: "Leída",
        resourceCreated: "Recurso creado",
        resourceName: "Recurso: {name}",
        title: "Notificaciones de recursos",
        unread: "No leída",
        uploader: "Subido por: {uploader}",
      },
      trash: {
        adminEmpty: "No hay recursos en la papelera.",
        adminTitle: "Papelera de recursos",
        deletedBy: "Eliminado por {user}",
        deletedOn: "Eliminado el {date}",
        deletionRoleAdmin: "Eliminado por un administrador",
        deletionRoleOwner: "Eliminado por el propietario",
        description:
          "Restaura recursos o elimínalos permanentemente del almacenamiento.",
        ownerEmpty: "No tienes recursos en la papelera.",
        ownerTitle: "Tu papelera de recursos",
        permanentConfirmationDescription:
          "¿Quieres eliminar {name} permanentemente? Se quitarán todos los archivos subidos, la vista previa, las versiones y el historial de descargas. Esta acción no se puede deshacer.",
        permanentConfirmationTitle: "Eliminar recurso permanentemente",
        permanentFailure:
          "No pudimos eliminar {name} permanentemente. Sigue en la papelera y puedes volver a intentarlo.",
        permanentSuccess: "{name} se eliminó permanentemente.",
        restoreConfirmationDescription:
          "¿Quieres restaurar {name} en Recursos?",
        restoreConfirmationTitle: "Restaurar recurso",
        restoreFailure: "No pudimos restaurar {name}. Inténtalo de nuevo.",
        restoreSuccess: "{name} se restauró.",
        softDeleteConfirmationDescription:
          "¿Quieres mover {name} a la papelera? Ya no aparecerá en Recursos ni estará disponible para descargar.",
        softDeleteConfirmationTitle: "Mover recurso a la papelera",
        softDeleteFailure:
          "No pudimos mover {name} a la papelera. Inténtalo de nuevo.",
        softDeleteSuccess: "{name} se movió a la papelera.",
      },
      upload: {
        browseFiles: "Examinar",
        description:
          "Comparte archivos con la comunidad de Pocket Trash. Todos los campos son obligatorios.",
        descriptionLabel: "Descripción",
        descriptionPlaceholder: "Describe este recurso",
        expired: "Esta sesión de carga venció. Inicia la carga de nuevo.",
        fileFailure:
          "No se pudo subir {filename}. Vuelve a intentar este archivo.",
        fileHelp:
          "Elige de 1 a {maxFiles} archivos. Cada archivo puede pesar hasta {maxFileSize}; la carga completa puede pesar hasta {maxSessionSize}.",
        fileTypes:
          "Tipos de archivo permitidos: STL, 3MF, STEP, STP, PDF, TXT, ZIP, JPEG, PNG y WebP.",
        filesLabel: "Archivos del recurso",
        finalizationFailure:
          "Tus archivos se subieron, pero no se pudo finalizar el recurso. Vuelve a intentarlo para completar la carga.",
        finalizing: "Finalizando tu carga…",
        imagesHelp:
          "Elige de 1 a {maxImages} imágenes. La primera imagen será la portada. Cada imagen puede pesar hasta {maxFileSize}; todos los archivos de esta carga pueden pesar hasta {maxSessionSize} en total.",
        imagesLabel: "Imágenes",
        imageTypes: "Tipos de imagen permitidos: JPEG, PNG y WebP.",
        nameLabel: "Nombre",
        namePlaceholder: "Nombre del recurso",
        newVersionTitle: "Subir una nueva versión de {name}",
        previewHelp:
          "Imagen opcional que se muestra en las tarjetas y los detalles del recurso.",
        previewLabel: "Imagen de vista previa",
        previewTypes: "Tipos de vista previa permitidos: JPEG, PNG y WebP.",
        progress: "Subiendo {filename}: {percent}%",
        retryFile: "Reintentar {filename}",
        sessionFailure: "No pudimos iniciar la carga. Inténtalo de nuevo.",
        success: "Se agregó tu recurso.",
        title: "Agregar recurso",
        versionSuccess: "La versión {version} se subió.",
      },
      validation: {
        duplicateFilename: "Quita el nombre de archivo duplicado {filename}.",
        fileTooLarge: "{filename} debe pesar {maxSize} o menos.",
        imageInvalidType: "Elige un tipo de imagen compatible.",
        imageTooLarge: "Cada imagen debe pesar {maxSize} o menos.",
        invalidFileType: "El tipo de archivo de {filename} no está permitido.",
        previewInvalidType:
          "Elige un tipo de imagen de vista previa compatible.",
        previewTooLarge:
          "La imagen de vista previa debe pesar {maxSize} o menos.",
        requiredCategory: "Selecciona al menos una categoría.",
        requiredDescription: "Escribe una descripción.",
        requiredFile: "Elige al menos un archivo de recurso.",
        requiredImage: "Elige al menos una imagen.",
        requiredName: "Escribe un nombre para el recurso.",
        sessionTooLarge: "La carga completa debe pesar {maxSize} o menos.",
        tooManyFiles: "Elige como máximo {maxFiles} archivos de recurso.",
        tooManyImages: "Elige como máximo {maxImages} imágenes.",
        unsafeFilename: "Cambia el nombre de {filename} antes de subirlo.",
      },
      visibility: {
        adminPrivateTooltip:
          "Un administrador marcó este recurso como privado. Solo un administrador puede hacerlo público.",
        private: "Privado",
        public: "Público",
      },
    },
    settings: {
      about: "",
      aboutDescription: "",
      currency: "Moneda",
      dark: "Oscuro",
      dimensionUnits: "Unidades de dimensiones",
      dimensions: "Dimensiones",
      displayCurrency: "Moneda de visualizacion",
      displayPreferences: "Preferencias de visualizacion para el archivo.",
      displayPreferencesMachinedPens:
        "Preferencias de visualizacion para el archivo de plumas maquinadas.",
      grams: "Gramos",
      inches: "Pulgadas",
      language: "Idioma",
      light: "Claro",
      millimeters: "Milimetros",
      settings: "Ajustes",
      system: "Sistema",
      theme: "Tema",
      weight: "Peso",
      weightUnits: "Unidades de peso",
      ounces: "Onzas",
    },
    sidebar: {
      close: "Cerrar barra lateral",
      description: "Muestra la barra lateral movil.",
      sidebar: "Barra lateral",
      toggle: "Alternar barra lateral",
    },
    status: {
      disabled: "Desactivada",
      enabled: "Activada",
      failedToLoad: "No se pudo cargar.",
    },
    storage: {
      sizeMiB: "{value} MiB",
    },
    upload: {
      finalizationFailure:
        "Tus archivos se cargaron, pero no se pudo finalizar la carga. Inténtalo de nuevo.",
      saveFailed: "No pudimos guardar tu carga. Inténtalo de nuevo.",
    },
  },
} satisfies LocalizationResource;
