import type { LocalizationResource } from "../types/localization.js";

/**
 * es-MX translations for Pocket Trash.
 *
 * This catalog is checked against `LocalizationResource` from
 * `src/types/localization.ts`. When adding a translation key, update that type
 * first, add the required English string in `src/localizations/en-US.ts`, then
 * run `pnpm localization:sync` so this locale gets any missing blank fields.
 * Blank strings fall back to `en-US` at runtime until translated.
 */
export const esMX = {
  app: {
    name: "",
  },
  action: {
    cancel: "Cancelar",
    save: "Guardar",
  },
  error: {
    generic: "Algo salio mal.",
  },
  locale: {
    current: "Idioma actual: {locale}",
  },
  web: {
    site: {
      name: "",
    },
    changelog: {
      allCategories: "Todas las categorías",
      copyFailed: "No se pudo copiar el enlace",
      copyLink: "Copiar enlace",
      dateModified: "Fecha de modificación",
      datePublished: "Fecha",
      empty: "Aún no hay entradas en el registro de cambios.",
      emptyCategory: "No hay entradas en esta categoría.",
      linkCopied: "Enlace copiado",
      nextPage: "Página siguiente",
      pageStatus: "Página {page} de {pageCount}",
      previousPage: "Página anterior",
    },
    action: {
      addCollection: "",
      addColor: "Agregar color",
      addFinish: "Agregar acabado",
      addFinishOption: "Agregar opción de acabado",
      addMaker: "",
      addMaterial: "",
      addProduct: "",
      addToCollection: "",
      archive: "Archivar",
      clearAllFilters: "Borrar todos los filtros",
      clearCover: "Quitar portada",
      clearSearch: "Borrar búsqueda",
      close: "Cerrar",
      confirmAdd: "",
      deleteCover: "",
      deleteImage: "Eliminar imagen",
      edit: "Editar",
      more: "Más",
      moreFilters: "Más filtros",
      moveFinishOptionDown: "Mover la opción de acabado hacia abajo",
      moveFinishOptionUp: "Mover la opción de acabado hacia arriba",
      removeFinishOption: "Quitar opción de acabado",
      removeSelection: "Quitar {name}",
      saveFlag: "Guardar bandera",
      search: "Buscar",
      selectCover: "Usar como portada",
      signIn: "Iniciar sesion",
      signOut: "Cerrar sesión",
      uploadImages: "Subir imágenes",
      view: "Ver",
      viewCollection: "Ver colección",
      viewItem: "Ver artículo",
      viewProductDetails: "Ver detalles del producto",
      visitProductPage: "Visitar pagina del producto",
    },
    admin: {
      audit: {
        action: "Acción",
        actor: "Actor",
        actorId: "ID del actor",
        after: "Después",
        before: "Antes",
        coverage: "La cobertura comienza el {date}",
        coveredDomains: "Dominios cubiertos: {domains}",
        deleteAction: "",
        deleteConfirmation: "",
        deletedUser: "Usuario eliminado",
        description:
          "Revisa los cambios administrativos y de productos registrados.",
        exportAction: "",
        exportDescription: "",
        exportReasonPlaceholder: "",
        exportSummary: "",
        exportTitle: "",
        fromDate: "Fecha inicial",
        metadata: "Metadatos",
        noEvents: "Ningún evento de auditoría coincide con estos filtros.",
        noValue: "Ninguno",
        occurred: "Ocurrió",
        olderEvents: "Eventos anteriores",
        owner: "Propietario",
        reason: "Motivo",
        target: "Objetivo",
        targetId: "ID del objetivo",
        targetType: "Tipo de objetivo",
        title: "Registro de auditoría",
        toDate: "Fecha final",
      },
      featureFlags: {
        actions: "Acciones",
        adminOnlyTargeting: "Segmentacion solo para admins",
        audience: "Audiencia",
        booleanControls:
          "Controles booleanos para superficies globales, privadas y beta.",
        description: "Descripcion",
        displayName: "Nombre visible",
        editFlag: "Editar bandera",
        emailUsernameOrName: "Email, usuario o nombre",
        featureFlags: "Banderas de funciones",
        flag: "Bandera",
        flags: "Banderas",
        globalDefaultEnabled: "Valor global activado",
        newFlag: "Nueva bandera",
        searchUsers: "Buscar usuarios",
        slugPlaceholder: "",
      },
      makers: {
        description:
          "Administra los perfiles de fabricantes y sus URL públicas.",
        editMaker: "Editar {name}",
        empty: "No se encontraron fabricantes.",
        imageAction: "{action} {fileName}",
        imagesEmpty: "Todavía no hay imágenes del fabricante.",
        rootUrl: "Sitio web",
        title: "Fabricantes",
      },
      users: {
        active: "Activo",
        ban: "Bloquear usuario",
        banned: "Bloqueado",
        description: "Busca usuarios y administra el acceso a sus cuentas.",
        noResults: "No se encontraron usuarios.",
        pendingBan: "Bloqueo pendiente",
        pendingUnban: "Desbloqueo pendiente",
        reasonPlaceholder: "Explica el motivo de esta decisión de acceso",
        title: "Acceso de usuarios",
        unban: "Desbloquear usuario",
        updated: "Se actualizó el acceso del usuario.",
        updateReason: "Actualizar motivo",
      },
      hub: {
        catalogImageTrash: "Papelera de imágenes del catálogo",
        description: "Administra Pocket Trash.",
        materials: "Materiales",
        title: "Panel de administración",
      },
      notifications: {
        title: "Notificaciones",
      },
      settings: {
        title: "Configuración de administración",
        linear: {
          title: "Linear",
          description:
            "Conecta Linear para planificar solicitudes de sugerencias aprobadas.",
          connect: "Conectar Linear",
          connectedAs: "Conectado como {name}",
          update: "Actualizar conexión",
          remove: "Eliminar conexión",
          needsUpdate:
            "Actualiza la conexión para conceder acceso de escritura.",
          actionFailed: "No pudimos actualizar la conexión de Linear.",
        },
      },
      trash: {
        title: "Papelera",
      },
    },
    archive: {
      closeSearch: "Cerrar busqueda",
      controls: "Controles del archivo",
      defaultPenDescription: "",
      filterDescription:
        "Filtra el archivo por categoria, tamano, material y mas.",
      filters: "Filtros",
      itemCount: "",
      noDescription: "",
      noItems: "Ningun articulo coincide con estos filtros.",
      searchPlaceholder: "Buscar...",
      searchProducts:
        "Buscar plumas por titulo, especificaciones o descripcion",
      sortLabel: "Ordenar",
      sortProducts: "Ordenar plumas",
      sortDescription: "Elige como ordenar el archivo.",
      footer: {
        fanMade: "Hecho por un fan; sin afiliacion con ningun fabricante.",
        productOwnership:
          "Los nombres, imagenes y descripciones de productos siguen siendo propiedad de sus respectivos duenos.",
        resourceFor: "Un recurso para",
        suggestionsOrContact: "Sugerencias o contacto:",
        discord: "y el Discord de Machined Pens.",
      },
      headline: {
        grip: "",
        mechanism: "",
        pen: "",
      },
      lightbox: {
        archived: "Archivada - ya no esta listada",
        closeProductDetails: "Cerrar detalles del producto",
        nextImage: "Siguiente imagen",
        previousImage: "Imagen anterior",
        released: "Publicado",
        specsDescription:
          "Especificaciones, materiales y detalles de lanzamiento de este producto.",
      },
      filter: {
        all: "todos",
        any: "cualquiera",
        matchMode: "Modo de coincidencia de {label}",
        bodyDetails: "",
        category: "",
        clip: "",
        finish: "",
        material: "",
        mechanism: "",
        refill: "",
        size: "",
        tipNose: "",
      },
      sort: {
        newestDrop: "Lanzamiento mas reciente",
        oldestDrop: "Lanzamiento mas antiguo",
        priceLowToHigh: "Precio de menor a mayor",
        priceHighToLow: "Precio de mayor a menor",
        weightLightToHeavy: "Peso de menor a mayor",
        weightHeavyToLight: "Peso de mayor a menor",
        diameterThinToThick: "Diametro de delgado a grueso",
        diameterThickToThin: "Diametro de grueso a delgado",
        titleAToZ: "Titulo A a Z",
      },
      spec: {
        diameter: "Diametro",
        length: "Longitud",
        model: "Modelo",
        price: "Precio",
        weight: "Peso",
      },
      state: {
        archived: "Archivada",
      },
    },
    catalog: {
      approval: {
        approve: "Aprobar producto",
        collectionItem: {
          approve: "Aprobar artículo de la colección",
          reject: "Rechazar artículo de la colección",
          title: "Aprobación del artículo de la colección",
        },
        reasonLabel: "Motivo de la decisión",
        reasonPlaceholder: "Explica esta decisión de aprobación",
        reject: "Rechazar producto",
        reverse: "Devolver a pendiente",
        status: {
          approved: "Aprobado",
          pending: "Pendiente de revisión",
          rejected: "Rechazado",
        },
        title: "Aprobación del producto",
      },
      collectionsWithProduct: "Colecciones con este producto",
      colorEffect: {
        fade: "Degradado",
        solid: "Sólido",
      },
      defaultButton: "",
      deletion: {
        action: "Eliminar producto permanentemente",
        blocked:
          "Este producto está en uso en una colección o en otro producto y no se puede eliminar.",
        confirmation:
          "Entiendo que la eliminación de este producto y sus imágenes no se puede deshacer.",
        description:
          "¿Eliminar {name} permanentemente? Se eliminarán sus imágenes, opciones de acabado, vínculos con materiales y especificaciones. Esta acción no se puede deshacer.",
        failed: "No pudimos eliminar este producto. Inténtalo de nuevo.",
        title: "Eliminar producto",
      },
      error: {
        bearingLength: "",
        colorHex: "Elige un color válido.",
        colorEffectRequired: "Selecciona un efecto de color.",
        colorEffectWithoutColors: "Agrega un color o quita el efecto de color.",
        descriptionLength: "",
        duplicate: "",
        duplicateComponent:
          "Cada acabado o color solo puede seleccionarse una vez.",
        duplicateFinishOption: "Esa opción de acabado ya está en la lista.",
        fadeColors: "Selecciona al menos dos colores para un degradado.",
        finishOptionRequired: "Agrega al menos una opción de acabado.",
        finishRequired: "Selecciona al menos un acabado.",
        form: "",
        positive: "",
        productFinishRequired:
          "Selecciona un acabado del producto o crea un acabado personalizado.",
        productMaterialRequired:
          "Selecciona un material ofrecido por este producto.",
        required: "",
        url: "",
      },
      field: {
        bearing: "",
        button: "",
        buttonDiameter: "",
        colorEffect: "Efecto de color",
        colorValue: "Valor del color",
        colors: "Colores",
        description: "Descripción",
        finishes: "Acabados",
        finishOptions: "Opciones de acabado",
        maker: "",
        makerProductUrl: "",
        materials: "",
        name: "",
        productType: "",
        rootUrl: "",
        slug: "",
        spinDiameter: "",
        thickness: "",
        thicknessWithButton: "",
        width: "",
      },
      filter: {
        description:
          "Filtra por tipo de producto, material, acabado, color y fabricante.",
        fadeName: "Degradado {colors}",
        moreOptions: "Más opciones de {label}",
        productTypeAll: "Todos los tipos de producto",
      },
      help: {
        collectionDescriptionOverride: "",
        makerProductUrl: "",
        markdownDescription: "",
      },
      images: {
        aspectRatioGuideLink: "Leer la guía de tamaño y resolución de imágenes",
        aspectRatioWarning:
          "Esta imagen no tiene una relación de aspecto de 4:3 y se recortará al mostrarse.",
      },
      finishOptionCount: "Opciones de acabado: {count}",
      finishPreview: "Vista previa: {finish}",
      materialCount: "Materiales: {count}",
      noProducts: "",
      notImplemented: "",
      selectColorEffect: "Selecciona un efecto de color",
      selectColors: "Selecciona colores",
      selectFinishes: "Selecciona acabados",
      selectFinishOption: "Selecciona una opción de acabado",
      selectMaker: "",
      selectMaterial: "Selecciona un material",
      selectMaterials: "",
      selectProductType: "",
    },
    slider: {
      productType: {
        slider: "Deslizador",
        plate: "Placa para deslizador",
        insert: "Inserto para deslizador",
      },
      alias: {
        canonicalLabel: "Término canónico: {label}",
        matchedContext: "Término coincidente: {alias}",
        preferredMakerLabel: "Término del fabricante: {alias}",
      },
      capability: {
        label: "Uso de insertos",
        bodyHosted: "Integrado en el cuerpo",
        insertDriven: "Basado en inserto",
        notRecorded: "Alojamiento de imanes no registrado",
        sliderBodyHoldsMagnets: "El cuerpo del deslizador sostiene los imanes",
        usesInserts: "Este deslizador usa insertos",
      },
      measurement: {
        basis: "Base de las medidas",
        setLevel: "Juego completo emparejado",
        setLevelHelp:
          "Las medidas y el peso de la placa y del inserto describen el juego completo emparejado.",
      },
      appearance: {
        label: "Apariencia",
        materialRequired: "El material es obligatorio",
        optional: "La apariencia es opcional",
        none: "Sin apariencia seleccionada",
        pattern: "Patrón",
        patterns: "Patrones",
        selectPattern: "Selecciona un patrón",
      },
      layout: {
        label: "Distribución de imanes",
        option: "{layout} — {count} clics",
        help: "{layout} tiene {rows} filas, {columns} posiciones longitudinales, {slots} espacios por lado y {clicks} clics.",
      },
      setup: {
        title: "Configuración de imanes",
        default: "Configuración predeterminada",
        defaultDescription:
          "La configuración vigente anunciada en el catálogo. No crea una configuración personalizada guardada.",
        advertisedDefault: "Predeterminada anunciada",
        availableOffers: "Configuraciones de inserto disponibles",
        offer: "Oferta de configuración",
        selectOffer: "Selecciona una oferta de configuración",
        custom: "Configuración personalizada",
        fromScratch: "Crear desde cero",
        liveCatalog: "Configuración vigente del catálogo",
        sourceNote: "Nota de la fuente",
        clickCount: "Cantidad de clics",
        clicks: "{count} clics",
        notRecorded: "No registrado",
      },
      magnet: {
        advanced: "",
        clear: "",
        configuration: "Configuración de imanes",
        configurations: "Configuraciones de imanes",
        deletePresetConfirmation: "",
        differentSides: "",
        layoutChanged: "",
        position: "",
        preset: "",
        presets: "",
        selectPreset: "",
        vocabularyLabel: "Etiqueta de configuración",
        halfA: "Mitad A",
        halfB: "Mitad B",
        slot: "Posición de imán",
        slots: "Posiciones de imanes",
        group: "Grupo de imanes",
        groups: "Grupos de imanes",
        size: "Tamaño del imán",
        grade: "Grado del imán",
        row: "Fila documentada",
        column: "Columna documentada",
        insertionPosition: "Posición de inserción {position}",
        state: {
          occupied: "Ocupada",
          empty: "Vacía",
          unknown: "Desconocida",
        },
      },
      relationship: {
        addInsert: "Agregar inserto",
        plates: "Placas",
        inserts: "Insertos",
        includedInsert: "Inserto incluido",
        includedPlates: "Placas incluidas",
        addPlates: "Agregar placas",
        includedComponents: "Componentes incluidos",
        included: "Incluido",
        installed: "Instalado",
        availableInsertOffers: "Ofertas de inserto disponibles",
        inclusionHelp:
          "Las piezas incluidas describen lo que se vende con este producto. No crean artículos de colección.",
      },
      component: {
        plateSet: "Juego de placas",
        insertSet: "Juego de insertos",
        spare: "Repuesto",
        installedPlate: "Placa instalada",
        installedInsert: "Inserto instalado",
        noPlate: "Sin placa instalada",
        noInsert: "Sin inserto instalado",
        createIncluded: "Crear componente incluido",
        linkExisting: "Vincular componente existente",
        install: "Instalar componente",
        uninstall: "Desinstalar componente",
        replace: "Reemplazar componente",
        detach: "Desvincular componente",
        moveAssembly: "Mover el conjunto completo",
        moveAssemblySummary:
          "Al mover este artículo también se mueven {count} artículos conectados del conjunto.",
        uninstallBeforeTransfer:
          "Desinstala este componente antes de instalarlo en otro deslizador.",
        deleteSliderKeepsComponents:
          "Al eliminar este deslizador, sus componentes quedan como repuestos independientes.",
        deleteComponentDetaches:
          "Al eliminar este componente instalado, se desvincula del conjunto.",
      },
      search: {
        label: "Buscar en el catálogo y las colecciones",
        placeholder:
          "Busca productos, fabricantes, tipos, alias o propietarios",
        matchedAliasContext: "Alias coincidente: {alias}",
        matchedTypeContext: "Tipo de producto coincidente: {type}",
        ownerMatchContext: "Propietario coincidente: {owner}",
        noResults:
          "Ningún producto o artículo de colección coincide con esta búsqueda.",
      },
      filter: {
        description:
          "Filtra por material, acabado, color, fabricante, tipo, patrón o componente exacto.",
        pattern: "Patrón",
        plate: "Placa para deslizador",
        spinnerButton: "Botón de spinner",
        any: "Coincidir con cualquier opción seleccionada",
        all: "Coincidir con todas las opciones seleccionadas",
        resultsAnnouncement: "{count} resultados coincidentes",
      },
      privacy: {
        inherited: "Privacidad heredada",
        inheritedDescription:
          "Este componente instalado sigue la privacidad de su deslizador o spinner principal.",
        inheritedHelp:
          "Usa el botón de información con un puntero, teclado o toque para saber por qué esta opción de privacidad es de solo lectura.",
        savedPreference:
          "Tu preferencia de privacidad guardada para el componente se restaura cuando se desvincula.",
        staffForcedPrivate:
          "El personal indicó que este componente debe permanecer privado.",
        blockingComponent: "{component} impide que este conjunto sea público.",
      },
      moderation: {
        blockedTitle: "Acción bloqueada",
        publicBlocked:
          "Este conjunto no puede ser público porque un componente instalado no está disponible o el personal lo marcó como privado.",
        installBlocked:
          "Este componente no se puede instalar porque su estado de moderación entra en conflicto con el conjunto.",
        unavailableComponent: "Componente no disponible",
      },
      validation: {
        capabilityRequired: "Elige si este deslizador usa insertos.",
        bodyHostedInsert: "Este deslizador no usa insertos.",
        insertMaterial: "Selecciona exactamente un material para un inserto.",
        alreadyInstalled:
          "Este componente ya está instalado en otro deslizador.",
        differentOwner:
          "Todos los artículos del conjunto deben tener el mismo propietario.",
        unapproved: "Solo se pueden instalar productos aprobados del catálogo.",
        exactProduct:
          "Selecciona una opción de este producto exacto del catálogo.",
        onePlate: "Un deslizador puede tener como máximo una placa instalada.",
        oneInsert:
          "Un deslizador basado en inserto puede tener como máximo un inserto instalado.",
        clickOption: "Selecciona una opción de clic vigente de este inserto.",
        completeConfiguration:
          "Las configuraciones del catálogo deben registrar todas las posiciones obligatorias.",
        unknownSlot:
          "Las configuraciones del catálogo no pueden contener posiciones desconocidas.",
        incompleteSlot:
          "Completa todas las posiciones de imanes antes de guardar.",
        overlappingGroup:
          "Una posición de imán solo puede pertenecer a un grupo.",
        positiveDimension: "Ingresa una dimensión mayor que cero.",
        crossConfiguration:
          "Los grupos de imanes no pueden hacer referencia a posiciones de otra configuración.",
        advertisedDefault:
          "Selecciona como máximo una opción predeterminada anunciada.",
      },
      confirmation: {
        createIncluded:
          "¿Crear este componente incluido como un nuevo artículo de colección?",
        linkIncluded:
          "¿Vincular un artículo de colección existente como este componente?",
        install: "¿Instalar {component} en {slider}?",
        uninstall: "¿Desinstalar {component} y conservarlo como repuesto?",
        replace:
          "¿Reemplazar {current} por {replacement}? El componente actual permanecerá como repuesto.",
        moveAssembly: "¿Mover todo el conjunto instalado a {collection}?",
        deleteStandalone:
          "¿Eliminar permanentemente este artículo independiente? Esta acción no se puede deshacer.",
        deleteInstalledComponent:
          "¿Eliminar permanentemente este componente y desvincularlo del conjunto?",
        deleteSlider:
          "¿Eliminar permanentemente este deslizador y conservar sus componentes como repuestos?",
      },
      empty: {
        noOffers: "No hay ofertas de configuración disponibles.",
        noSearchResults:
          "Ningún producto de deslizador coincide con esta búsqueda.",
        noFilterResults:
          "Ningún producto de deslizador coincide con estos filtros.",
      },
    },
    collections: {
      add: {
        title: "",
      },
      cover: {
        clearConfirmation:
          "¿Quieres quitar la portada actual? La imagen permanecerá en la galería.",
        current: "Portada actual",
        deleteConfirmation: "",
        history: "",
      },
      directory: {
        avatar: "",
        itemCount: "Artículos de la colección: {count}",
        matchingItemCount: "{matching} de {total} artículos de la colección",
      },
      deletion: {
        deleteConfirmation:
          "Entiendo que eliminar esta colección, sus artículos y sus imágenes no se puede deshacer.",
        deleteChoice: "Eliminar permanentemente la colección y sus artículos",
        destination: "Colección de destino",
        itemAction: "Eliminar artículo permanentemente",
        itemConfirmation:
          "Entiendo que eliminar este artículo y sus imágenes no se puede deshacer.",
        itemDescription:
          "¿Quieres eliminar permanentemente {name} de su colección? Se eliminarán sus imágenes y su selección de acabado. Se conservarán los artículos vinculados y los productos del catálogo; se quitará cualquier vínculo de componente instalado con este artículo y los componentes instalados en este artículo quedarán como repuestos.",
        moveAction: "Mover artículos y eliminar",
        moveChoice: "Mover artículos y luego eliminar la colección",
        moveConfirmation:
          "Entiendo que esta colección y sus imágenes de portada se eliminarán permanentemente. Se conservarán los artículos movidos y sus imágenes.",
        moveSummary: "Mover {count} artículos a {destination}.",
        noDestination: "Crea otra colección antes de mover artículos.",
        open: "Eliminar o archivar",
      },
      duplicateWarning: "",
      edit: {
        noFields: "",
        title: "",
      },
      empty: "",
      emptyCollections: "",
      error: {
        chooseCollection: "",
        syncIncomplete: "",
        upload:
          "La colección se guardó, pero no se pudieron subir sus imágenes. Inténtalo de nuevo desde Editar colección.",
      },
      gallery: {
        deleteConfirmation:
          "¿Quieres eliminar permanentemente esta imagen de la colección? Esta acción no se puede deshacer.",
        imagesHelp:
          "Elige de 1 a {maxImages} imágenes. Si la colección no tiene portada, la primera imagen será la portada. Cada imagen puede pesar hasta {maxFileSize}; todos los archivos de esta carga pueden pesar hasta {maxSessionSize} en total.",
        nextPage: "Página siguiente",
        owner: "Propietario: {owner}",
        pageStatus: "Página {page} de {pageCount}",
        previousPage: "Página anterior",
        title: "Galería",
      },
      field: {
        collection: "",
        cover: "",
        description: "",
        displayName: "Nombre para mostrar",
        name: "",
        summary: "Resumen",
      },
      finishChoice: {
        custom: "Acabado personalizado",
        product: "Acabado del producto",
      },
      placeholder: {
        description: "",
        name: "",
        summary: "Resume esta colección",
      },
      select: {
        addNew: "",
        placeholder: "",
      },
      visibility: {
        privateCallout: "",
      },
    },
    currency: {
      aud: "",
      cad: "",
      chf: "",
      eur: "",
      gbp: "",
      jpy: "",
      nzd: "",
      usd: "",
    },
    error: {
      expectedJsonRequestBody: "",
      invalidCurrencyCode: "",
      invalidDimensionUnit: "",
      invalidLocale: "",
      invalidLogClientKey: "",
      invalidTheme: "",
      invalidWeightUnit: "",
      missingSetting: "",
      settingsSaveFailed: "",
      userSettingsObject: "",
    },
    erasure: {
      self: {
        title: "Eliminar cuenta",
        description:
          "Borra permanentemente tu cuenta de Pocket Trash y los datos vinculados con ella.",
        open: "Eliminar mi cuenta",
        dialogTitle: "¿Eliminar tu cuenta?",
        dialogIntro:
          "La eliminación comienza de inmediato y no se puede cancelar.",
        deletedData:
          "Se eliminarán tu perfil, configuración, colecciones, elementos de colecciones, recursos y archivos cargados.",
        productsRemain:
          "Los productos que enviaste pueden permanecer en el catálogo sin atribución a ti.",
        retention:
          "Las copias de seguridad, cachés y registros de seguridad pueden conservar datos limitados hasta que venzan sus periodos de retención documentados.",
        publicCopies:
          "Las copias guardadas o compartidas por otras personas no se pueden retirar.",
        confirm:
          "Entiendo que esta acción es permanente y no se puede cancelar.",
        submit: "Eliminar permanentemente mi cuenta",
        failure:
          "No se pudo iniciar la eliminación de la cuenta. Inténtalo de nuevo.",
      },
      status: {
        title: "Eliminación de cuenta",
        processing: "Eliminación en curso",
        processingDescription:
          "Tu cuenta está restringida mientras Pocket Trash elimina los datos vinculados con ella.",
        needsSupport: "La eliminación necesita asistencia",
        needsSupportDescription:
          "No pudimos completar automáticamente todos los pasos de eliminación. Comunícate con soporte e incluye el ID de solicitud que aparece abajo.",
        completed: "Cuenta eliminada",
        completedDescription:
          "Tu cuenta de Pocket Trash y los datos vinculados con ella en los sistemas activos se eliminaron.",
        requestId: "ID de solicitud: {requestId}",
        support: "Contactar a soporte",
      },
      admin: {
        navigation: "Eliminación de cuentas",
        title: "Eliminación de cuentas",
        description:
          "Inicia o reintenta una solicitud de privacidad verificada. No ingreses información personal en la referencia.",
        emailLabel: "Correo de la cuenta de Clerk",
        emailPlaceholder: "usuario@ejemplo.com",
        findTarget: "Buscar cuenta",
        findingTarget: "Buscando cuenta…",
        targetNotFound: "Ninguna cuenta de Clerk coincide con ese correo.",
        targetLabel: "Cuenta objetivo",
        verificationMethodLabel: "¿Cómo se verificó la solicitud?",
        authenticatedRequest: "Solicitud de privacidad autenticada",
        verifiedEmail: "Correo de Clerk verificado manualmente",
        referenceLabel: "Referencia opaca de la solicitud",
        referenceDescription:
          "Usa un ID de ticket o solicitud. No ingreses nombres, correos electrónicos ni detalles de la solicitud.",
        start: "Iniciar eliminación",
        starting: "Iniciando eliminación…",
        requestTitle: "Solicitud de eliminación",
        statusLabel: "Estado: {status}",
        errorLabel: "Código de error: {errorCode}",
        retry: "Reintentar eliminación",
        retrying: "Reintentando eliminación…",
        failure: "La acción de eliminación falló.",
      },
      productNotice:
        "Los productos que envíes pueden permanecer en el catálogo sin atribución después de que se elimine tu cuenta.",
    },
    feedback: {
      title: "Sugerencias",
      board: {
        empty: "No hay sugerencias activas que coincidan con tu búsqueda.",
        error: "No pudimos cargar las sugerencias.",
        loading: "Cargando sugerencias…",
        searchLabel: "Buscar sugerencias",
        searchPlaceholder: "Buscar solicitudes",
      },
      details: {
        open: "Ver detalles de {title}",
        title: "Detalles de la solicitud",
      },
      duplicates: {
        description: "Estas solicitudes pueden corresponder a tu idea.",
        submitAnyway: "Enviar de todos modos",
        title: "Solicitudes similares",
        upvote: "Votar por esta solicitud",
      },
      new: {
        title: "Enviar sugerencia",
        description: "Comparte una idea o reporta un problema.",
        titleLabel: "Título",
        titleHelp: "Máximo 120 caracteres.",
        descriptionHelp: "Máximo 5,000 caracteres.",
        categoryLabel: "Categoría (opcional)",
        categoryPlaceholder: "Selecciona una categoría",
        submit: "Enviar solicitud",
        submitting: "Enviando...",
        success: "Sugerencia enviada.",
        failure: "No pudimos enviar esta solicitud.",
        limit: "Puedes tener hasta 60 solicitudes activas.",
      },
      myRequests: {
        title: "Mis solicitudes",
        empty: "Aún no has enviado ninguna solicitud.",
        error: "No pudimos cargar tus solicitudes.",
        loading: "Cargando solicitudes…",
        nextPage: "Página siguiente",
        noResults: "Ninguna solicitud coincide con tu búsqueda.",
        previousPage: "Página anterior",
        searchLabel: "Buscar mis solicitudes",
        searchPlaceholder: "Buscar solicitudes",
      },
      admin: {
        navigation: {
          allActive: "Todas activas",
          active: "Planificadas",
          archive: "Archivo",
          requests: "Solicitudes",
        },
        plan: {
          action: "Planificar",
          title: "Planificar solicitud",
          typeLabel: "Crear en Linear",
          issue: "Incidencia",
          project: "Proyecto",
          assignIssue: "Asignarme",
          leadProject: "Asignarme como líder del proyecto",
          labels: "Etiquetas",
          submit: "Crear y planificar",
          loading: "Cargando opciones de Linear…",
          success: "Solicitud planificada en Linear.",
          failure:
            "No pudimos crear esto en Linear. Puedes volver a intentarlo de forma segura.",
          connectionRequired:
            "Conecta o actualiza Linear en Configuración de administración antes de planificar.",
          settingsLink: "Abrir Configuración de administración",
        },
        sync: {
          action: "Sincronizar",
          connectionRequired:
            "Conecta o actualiza Linear en Configuración de administración antes de sincronizar.",
          failure: "No pudimos sincronizar este estado desde Linear.",
          success: "Estado de la sugerencia sincronizado.",
        },
        table: {
          actions: "Acciones",
          category: "Categoría",
          status: "Estado",
          submitted: "Enviada",
          submitter: "Remitente",
          title: "Título",
          updated: "Actualizada",
          votes: "Votos",
        },
        sort: {
          ascending: "Ordenar {column} de forma ascendente",
          descending: "Ordenar {column} de forma descendente",
          remove: "Quitar orden por {column}",
        },
        requests: {
          title: "Solicitudes de sugerencias",
          empty: "No hay solicitudes pendientes.",
          error: "No pudimos cargar las solicitudes pendientes.",
          loading: "Cargando solicitudes pendientes…",
          approve: "Aprobar",
          saveAndApprove: "Guardar y aprobar",
          deny: "Rechazar",
          categoryRequired: "Selecciona una categoría antes de aprobar.",
          approved: "Solicitud aprobada.",
          denied: "Solicitud rechazada.",
          detailsOpen: "Administrar {title}",
          detailsTitle: "Administrar solicitud",
          merge: "Combinar solicitud",
          mergeTargetLabel: "Combinar con",
          mergeTargetPlaceholder: "Selecciona una solicitud activa",
          merged: "Solicitud combinada.",
          planRecoveryRequired:
            "Recupera el intento de planificación de Linear sin terminar antes de rechazar esta solicitud.",
          updated: "Solicitud actualizada.",
          actionFailed: "No pudimos actualizar esta solicitud.",
          previousPage: "Página anterior",
          nextPage: "Página siguiente",
        },
        active: {
          empty: "No hay sugerencias planificadas.",
          error: "No pudimos cargar las sugerencias planificadas.",
          loading: "Cargando sugerencias planificadas…",
          nextPage: "Página siguiente",
          previousPage: "Página anterior",
          searchLabel: "Buscar sugerencias planificadas",
          searchPlaceholder: "Buscar solicitudes planificadas",
          title: "Planificadas",
        },
        archive: {
          allStatuses: "Todos los estados",
          empty: "El archivo de sugerencias está vacío.",
          error: "No pudimos cargar el archivo de sugerencias.",
          loading: "Cargando el archivo de sugerencias…",
          nextPage: "Página siguiente",
          noResults: "Ninguna sugerencia archivada coincide con estos filtros.",
          previousPage: "Página anterior",
          searchLabel: "Buscar sugerencias archivadas",
          searchPlaceholder: "Buscar solicitudes archivadas",
          statusLabel: "Estado",
          title: "Archivo de sugerencias",
        },
      },
      status: {
        canceled: "Cancelada",
        completed: "Completada",
        denied: "Rechazada",
        inProgress: "En curso",
        merged: "Combinada",
        pending: "Pendiente",
        planned: "Planificada",
        requested: "Solicitada",
      },
      vote: {
        add: "Votar",
        failure: "No pudimos actualizar tu voto.",
        permanent: "Tu voto de envío es permanente.",
        remove: "Quitar voto",
      },
      category: {
        productType: "Tipo de producto",
        feature: "Funcionalidad",
        improvement: "Mejora",
        bug: "Error",
        unset: "Sin definir",
      },
      metadata: {
        submittedOn: "Enviada el {date}",
        submittedBy: "Enviada por {submitter}",
        votes: "{count} votos",
      },
      notification: {
        completed: "Completada",
        description:
          "Revisa la actividad de sugerencias enviadas y completadas.",
        empty: "No hay notificaciones de sugerencias.",
        submitted: "Enviada",
        title: "Notificaciones de sugerencias",
      },
    },
    footer: {
      discordNewTab: "Discord (se abre en una pestaña nueva)",
      tagline: "Hecho por fans de EDC para fans de EDC",
      xNewTab: "X (se abre en una pestaña nueva)",
    },
    help: {
      comingSoon: "Próximamente.",
      contact: "Contacto",
      dateModified: "Fecha de modificación",
      datePublished: "Fecha",
      developmentCallout: "Esta página todavía está en desarrollo.",
      topics: "Temas de ayuda",
    },
    markdownEditor: {
      mode: {
        visual: "",
        source: "",
      },
      toolbar: {
        heading1: "",
        heading2: "",
        heading3: "",
        bold: "",
        italic: "",
        strikethrough: "",
        link: "",
        unorderedList: "",
        orderedList: "",
        table: "",
        horizontalRule: "",
        blockquote: "",
      },
      link: {
        text: "",
        url: "",
        insert: "",
        update: "",
        remove: "",
        invalidUrl: "",
      },
      status: {
        loading: "",
        fallback: "",
      },
      count: {
        characters: {
          normal: "",
          warning: "",
          limitReached: "",
          overLimit: "",
        },
        words: {
          normal: "",
          warning: "",
          limitReached: "",
          overLimit: "",
        },
      },
    },
    materials: {
      admin: {
        addTitle: "Agregar material",
        created: "Se agregó el material.",
        description: "Agrega y edita los detalles e imágenes de materiales.",
        editTitle: "Editar material",
        empty: "No se encontraron materiales.",
        saved: "Se guardó el material.",
        slugHelp: "El slug es permanente y no se puede cambiar.",
        title: "Materiales",
      },
      count: {
        collectionItems: "Artículos de colección: {count}",
        products: "Productos: {count}",
      },
      detail: {
        collectionItems: "Artículos de colección",
        collectionItemsPagination: "Páginas de artículos de colección",
        noCollectionItems:
          "Aún no hay artículos de colección que usen este material.",
        noProducts: "Aún no hay productos que usen este material.",
        products: "Productos",
        productsPagination: "Páginas de productos",
      },
      directory: {
        description:
          "Explora los materiales utilizados por productos y colecciones.",
        empty: "Aún no hay materiales disponibles.",
        other: "Otros",
        popular: "Materiales populares",
        tableOfContents: "Materiales de la A a la Z",
        title: "Materiales",
      },
      image: {
        alt: "Imagen de {name}",
        archiveConfirmation: "¿Quieres archivar esta imagen del material?",
        empty: "No se han agregado imágenes.",
        placeholder: "No hay imagen disponible para {name}",
        restore: "Restaurar imagen",
        restoreConfirmation: "¿Quieres restaurar esta imagen del material?",
        uploadFailed:
          "Se guardó el material, pero no se pudieron subir sus imágenes. Inténtalo de nuevo desde Editar material.",
        uploadHelp:
          "Elige hasta {maxImages} imágenes. Cada imagen puede pesar hasta {maxFileSize}; todos los archivos de esta carga pueden pesar hasta {maxSessionSize} en total.",
      },
      validation: {
        duplicateImage: "Esta imagen ya se agregó.",
      },
    },
    makers: {
      collectionItems: "Artículos de colección",
      collectionItemsPagination: "Artículos de colección del fabricante",
      collectionItemCount: "Artículos de colección: {count}",
      detailDescription:
        "Explora productos y artículos de colección públicos de {name}.",
      directoryDescription:
        "Explora todos los fabricantes representados en el catálogo de Pocket Trash.",
      empty: "No se encontraron fabricantes.",
      imageAlt: "Imagen del fabricante {name}",
      imageCount: "Imágenes: {count}",
      noCollectionItems: "Todavía no hay artículos de colección públicos.",
      noProducts: "Todavía no hay productos públicos.",
      other: "Otros",
      popular: "Fabricantes populares",
      products: "Productos",
      productsPagination: "Productos del fabricante",
      productCount: "Productos: {count}",
      productMakerAttribution: "{productType} · {maker}",
      tableOfContents: "Directorio de fabricantes",
      visitWebsite: "Visitar el sitio web del fabricante",
    },
    navigation: {
      account: "Cuenta",
      accountMenu: "Menu de cuenta",
      admin: "Administración",
      betaFeatures: "Funciones beta",
      changelog: "Registro de cambios",
      collections: "Colecciones",
      contact: "Contacto",
      help: "Ayuda",
      home: "Inicio",
      language: "Idioma",
      logOut: "Cerrar sesion",
      materials: "Materiales",
      makers: "Fabricantes",
      privacy: "Privacidad",
      products: "",
      resources: "",
      selectLanguage: "Seleccionar idioma",
      termsOfService: "Términos del servicio",
      user: "Usuario",
    },
    locale: {
      enUS: "",
      esMX: "",
    },
    page: {
      betaFeatures: {
        empty: "No hay funciones beta disponibles.",
      },
      collections: {
        empty: "Las colecciones estaran disponibles mas adelante.",
      },
      error: {
        copied: "Copiado",
        copyDetails: "Copiar detalles del error",
        copyFailed: "No se pudo copiar",
        description: "No pudimos cargar esta página. Inténtalo de nuevo.",
        retry: "Reintentar",
        retrying: "Reintentando…",
        returnHome: "Volver al inicio",
        technicalDetails: "Detalles técnicos",
        title: "Algo salió mal",
      },
      notFound: {
        description: "Esta pagina no existe o ya no esta disponible.",
        returnHome: "Volver al inicio",
        returnToArchive: "Volver al archivo",
        title: "No encontrado",
        unavailable: "Pagina no disponible",
      },
      resources: {
        stub: "",
      },
    },
    resources: {
      action: {
        accept: "Aceptar",
        add: "Agregar recurso",
        closeImage: "Cerrar imagen",
        collapseVersion: "Contraer la versión {version}",
        collapseVersionHistory: "Contraer el historial de versiones",
        delete: "Mover a la papelera",
        details: "Detalles",
        download: "Descargar",
        edit: "Editar",
        expandVersion: "Expandir la versión {version}",
        expandVersionHistory: "Expandir el historial de versiones",
        markPrivate: "Marcar como privado",
        nextImage: "Imagen siguiente",
        permanentlyDelete: "Eliminar permanentemente",
        previousImage: "Imagen anterior",
        removeFile: "Quitar archivo",
        restore: "Restaurar",
        retry: "Reintentar",
        saveChanges: "Guardar cambios",
        upload: "Agregar recurso",
        uploadNewVersion: "Subir nueva versión",
      },
      add: {
        title: "Agregar recurso",
      },
      category: {
        all: "Todas las categorías",
        create: "Crear “{category}”",
        filterLabel: "Filtrar por categoría",
        label: "Categorías",
        noResults: "No se encontraron categorías.",
        remove: "Quitar {category}",
        search: "Buscar categorías",
        select: "Selecciona una o más categorías",
        selectedCount: "Categorías seleccionadas: {count}",
      },
      detail: {
        categories: "Categorías",
        currentVersion: "Versión actual",
        downloadCount: "Descargas: {count}",
        fileSize: "Tamaño: {size}",
        fileTypeFallback: "Archivo",
        filename: "Archivo: {filename}",
        imageAlt: "Imagen de {name}",
        noImage: "No hay imagen disponible",
        noPreview: "Sin imagen de vista previa",
        notFound: "Este recurso no está disponible.",
        openImage: "Abrir {name}",
        previewAlt: "Vista previa de {name}",
        sharedBy: "Compartido por",
        totalDownloadCount: "Descargas totales: {count}",
        updatedOn: "Actualizado el {date}",
        uploadedBy: "Subido por {uploader}",
        uploadedOn: "Subido el {date}",
        version: "Versión {version}",
        versionHistory: "Historial de versiones",
        versionUploadedOn: "Versión {version}, subida el {date}",
      },
      directory: {
        description:
          "Explora archivos compartidos por la comunidad de Pocket Trash.",
        empty: "Todavía no se han subido recursos.",
        emptyFiltered:
          "Ningún recurso coincide con estos filtros de categoría.",
        filters: "Filtros de recursos",
        invalidFilter: "Uno o más filtros de categoría no son válidos.",
        loading: "Cargando recursos…",
        searchPlaceholder: "Buscar recursos",
        title: "Recursos",
      },
      error: {
        archiveDownloadFallback:
          "Los archivos siguen disponibles individualmente en la página de detalles del recurso.",
        deleteUnauthorized: "No puedes eliminar este recurso.",
        downloadAccess: "No tienes acceso para descargar este archivo.",
        downloadUnavailable:
          "No se pudo crear un enlace de descarga para {filename}. Inténtalo de nuevo.",
        editFailed: "No pudimos actualizar este recurso. Inténtalo de nuevo.",
        loadDetail: "No pudimos cargar este recurso. Inténtalo de nuevo.",
        loadDirectory: "No pudimos cargar los recursos. Inténtalo de nuevo.",
        loadManagement: "No pudimos cargar tus recursos. Inténtalo de nuevo.",
        permanentDeleteUnauthorized:
          "Solo un administrador puede eliminar este recurso permanentemente.",
        previewAccess: "No tienes acceso a esta imagen de vista previa.",
        previewUnavailable:
          "No se pudo crear un enlace para la imagen de vista previa. Inténtalo de nuevo.",
        resourceNotFound: "Recurso no encontrado.",
        restoreUnauthorized: "No puedes restaurar este recurso.",
        saveFailed: "No pudimos guardar este recurso. Inténtalo de nuevo.",
      },
      management: {
        description: "Administra tus cargas y publica nuevas versiones.",
        editDescription:
          "Actualiza los detalles del recurso sin reemplazar los archivos subidos.",
        editResources: "Editar recursos",
        editTitle: "Editar {name}",
        empty: "Todavía no has subido ningún recurso.",
        metadataOnly:
          "Para reemplazar archivos, sube una nueva versión. Las versiones anteriores seguirán disponibles.",
        title: "Tus recursos",
      },
      moderation: {
        confirmationDescription:
          "¿Quieres retirar {name} de Recursos? La persona que lo subió y los administradores aún podrán verlo.",
        confirmationTitle: "Marcar recurso como privado",
        failure: "No pudimos retirar este recurso. Inténtalo de nuevo.",
        privateBadge: "Retirado",
        privateReason: "Motivo: {reason}",
        privateSince: "Retirado el {date}",
        reasonLabel: "Motivo del retiro",
        reasonPlaceholder: "Explica por qué se debe retirar este recurso",
        reasonRequired: "Se requiere un motivo.",
        success: "{name} ahora está retirado.",
      },
      notification: {
        acceptFailed:
          "No pudimos marcar esta notificación como leída. Inténtalo de nuevo.",
        accepted: "Notificación marcada como leída.",
        categories: "Categorías: {categories}",
        categoryCreated: "Categoría creada",
        categoryName: "Categoría: {name}",
        createdAt: "Creada el {date}",
        description: "Revisa la actividad nueva de recursos y categorías.",
        empty: "No hay notificaciones de recursos.",
        read: "Leída",
        resourceCreated: "Recurso creado",
        resourceName: "Recurso: {name}",
        title: "Notificaciones de recursos",
        unread: "No leída",
        uploader: "Subido por: {uploader}",
      },
      trash: {
        adminEmpty: "No hay recursos en la papelera.",
        adminTitle: "Papelera de recursos",
        deletedBy: "Eliminado por {user}",
        deletedOn: "Eliminado el {date}",
        deletionRoleAdmin: "Eliminado por un administrador",
        deletionRoleOwner: "Eliminado por el propietario",
        description:
          "Restaura recursos o elimínalos permanentemente del almacenamiento.",
        ownerEmpty: "No tienes recursos en la papelera.",
        ownerTitle: "Tu papelera de recursos",
        permanentConfirmationDescription:
          "¿Quieres eliminar {name} permanentemente? Se quitarán todos los archivos subidos, la vista previa, las versiones y el historial de descargas. Esta acción no se puede deshacer.",
        permanentConfirmationTitle: "Eliminar recurso permanentemente",
        permanentFailure:
          "No pudimos eliminar {name} permanentemente. Sigue en la papelera y puedes volver a intentarlo.",
        permanentSuccess: "{name} se eliminó permanentemente.",
        restoreConfirmationDescription:
          "¿Quieres restaurar {name} en Recursos?",
        restoreConfirmationTitle: "Restaurar recurso",
        restoreFailure: "No pudimos restaurar {name}. Inténtalo de nuevo.",
        restoreSuccess: "{name} se restauró.",
        softDeleteConfirmationDescription:
          "¿Quieres mover {name} a la papelera? Ya no aparecerá en Recursos ni estará disponible para descargar.",
        softDeleteConfirmationTitle: "Mover recurso a la papelera",
        softDeleteFailure:
          "No pudimos mover {name} a la papelera. Inténtalo de nuevo.",
        softDeleteSuccess: "{name} se movió a la papelera.",
      },
      upload: {
        browseFiles: "Examinar",
        description:
          "Comparte archivos con la comunidad de Pocket Trash. Todos los campos son obligatorios.",
        descriptionLabel: "Descripción",
        descriptionPlaceholder: "Describe este recurso",
        expired: "Esta sesión de carga venció. Inicia la carga de nuevo.",
        fileFailure:
          "No se pudo subir {filename}. Vuelve a intentar este archivo.",
        fileHelp:
          "Elige de 1 a {maxFiles} archivos. Cada archivo puede pesar hasta {maxFileSize}; la carga completa puede pesar hasta {maxSessionSize}.",
        fileTypes:
          "Tipos de archivo permitidos: STL, 3MF, STEP, STP, PDF, TXT, ZIP, JPEG, PNG, WebP y AVIF.",
        filesLabel: "Archivos del recurso",
        finalizationFailure:
          "Tus archivos se subieron, pero no se pudo finalizar el recurso. Vuelve a intentarlo para completar la carga.",
        finalizing: "Finalizando tu carga…",
        imagesHelp:
          "Elige de 1 a {maxImages} imágenes. La primera imagen será la portada. Cada imagen puede pesar hasta {maxFileSize}; todos los archivos de esta carga pueden pesar hasta {maxSessionSize} en total.",
        imagesLabel: "Imágenes",
        imageTypes: "Tipos de imagen permitidos: JPEG, PNG, WebP y AVIF.",
        nameLabel: "Nombre",
        namePlaceholder: "Nombre del recurso",
        newVersionTitle: "Subir una nueva versión de {name}",
        previewHelp:
          "Imagen opcional que se muestra en las tarjetas y los detalles del recurso.",
        previewLabel: "Imagen de vista previa",
        previewTypes:
          "Tipos de vista previa permitidos: JPEG, PNG, WebP y AVIF.",
        progress: "Subiendo {filename}: {percent}%",
        retryFile: "Reintentar {filename}",
        sessionFailure: "No pudimos iniciar la carga. Inténtalo de nuevo.",
        success: "Se agregó tu recurso.",
        title: "Agregar recurso",
        versionSuccess: "La versión {version} se subió.",
      },
      validation: {
        duplicateFilename: "Quita el nombre de archivo duplicado {filename}.",
        fileTooLarge: "{filename} debe pesar {maxSize} o menos.",
        imageInvalidType: "Elige un tipo de imagen compatible.",
        imageTooLarge: "Cada imagen debe pesar {maxSize} o menos.",
        invalidFileType: "El tipo de archivo de {filename} no está permitido.",
        previewInvalidType:
          "Elige un tipo de imagen de vista previa compatible.",
        previewTooLarge:
          "La imagen de vista previa debe pesar {maxSize} o menos.",
        requiredCategory: "Selecciona al menos una categoría.",
        requiredDescription: "Escribe una descripción.",
        requiredFile: "Elige al menos un archivo de recurso.",
        requiredImage: "Elige al menos una imagen.",
        requiredName: "Escribe un nombre para el recurso.",
        sessionTooLarge: "La carga completa debe pesar {maxSize} o menos.",
        tooManyFiles: "Elige como máximo {maxFiles} archivos de recurso.",
        tooManyImages: "Elige como máximo {maxImages} imágenes.",
        unsafeFilename: "Cambia el nombre de {filename} antes de subirlo.",
      },
      visibility: {
        adminPrivateTooltip:
          "Un administrador marcó este recurso como privado. Solo un administrador puede hacerlo público.",
        private: "Privado",
        public: "Público",
      },
    },
    settings: {
      about: "",
      aboutDescription: "",
      currency: "Moneda",
      dark: "Oscuro",
      dimensionUnits: "Unidades de dimensiones",
      dimensions: "Dimensiones",
      displayCurrency: "Moneda de visualizacion",
      displayPreferences: "Preferencias de visualizacion para el archivo.",
      displayPreferencesMachinedPens:
        "Preferencias de visualizacion para el archivo de plumas maquinadas.",
      grams: "Gramos",
      inches: "Pulgadas",
      language: "Idioma",
      light: "Claro",
      millimeters: "Milimetros",
      settings: "Ajustes",
      system: "Sistema",
      theme: "Tema",
      weight: "Peso",
      weightUnits: "Unidades de peso",
      ounces: "Onzas",
    },
    sidebar: {
      adminMenu: "Menú de administración",
      close: "Cerrar barra lateral",
      description: "Muestra la barra lateral movil.",
      profile: "Perfil",
      sidebar: "Barra lateral",
      toggle: "Alternar barra lateral",
    },
    status: {
      disabled: "Desactivada",
      enabled: "Activada",
      failedToLoad: "No se pudo cargar.",
    },
    storage: {
      sizeMiB: "{value} MiB",
    },
    upload: {
      finalizationFailure:
        "Tus archivos se cargaron, pero no se pudo finalizar la carga. Inténtalo de nuevo.",
      saveFailed: "No pudimos guardar tu carga. Inténtalo de nuevo.",
    },
  },
} satisfies LocalizationResource;
